// CCTV: a surveillance camera view. Figures walk through a night scene (night vision,
// thermal or grey); a targeting box jumps to a new one every few beats with a label;
// REC blinks on the beat, a camera number and a running timestamp sit in the corners;
// scanlines, a rolling bar, grain and a line glitch on the kick.
// Params are p_* uniforms; ranges and defaults are in cctv.json.
//
// @messages: REC|CAM|SUBJECT IDENTIFIED|TRACKING|MOTION DETECTED|MATCH 98.7|LIVE|RESTRICTED AREA|0123456789:
uniform float p_palette, p_people, p_walk, p_boxes, p_every, p_label, p_rec, p_stamp, p_cam,
              p_grain, p_scan, p_roll, p_vignette, p_glitch, p_zoom, p_beat;

#define TAU 6.2831853

// <text>
// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand.
#define CH_A 1.0
#define CH_B 2.0
#define CH_C 3.0
#define CH_D 4.0
#define CH_E 5.0
#define CH_F 6.0
#define CH_G 7.0
#define CH_H 8.0
#define CH_I 9.0
#define CH_J 10.0
#define CH_K 11.0
#define CH_L 12.0
#define CH_M 13.0
#define CH_N 14.0
#define CH_O 15.0
#define CH_R 16.0
#define CH_S 17.0
#define CH_T 18.0
#define CH_U 19.0
#define CH_V 20.0
#define CH_0 21.0
#define CH_1 22.0
#define CH_2 23.0
#define CH_3 24.0
#define CH_4 25.0
#define CH_5 26.0
#define CH_6 27.0
#define CH_7 28.0
#define CH_8 29.0
#define CH_9 30.0
vec2 glyph(float c) {
  if (c < 0.5) return vec2(0.0);
  if (c < 1.5) return vec2(1033774.0, 17969.0);   // A
  if (c < 2.5) return vec2(509487.0, 15921.0);   // B
  if (c < 3.5) return vec2(34350.0, 14881.0);   // C
  if (c < 4.5) return vec2(575023.0, 15921.0);   // D
  if (c < 5.5) return vec2(492607.0, 31777.0);   // E
  if (c < 6.5) return vec2(492607.0, 1057.0);   // F
  if (c < 7.5) return vec2(951854.0, 31281.0);   // G
  if (c < 8.5) return vec2(1033777.0, 17969.0);   // H
  if (c < 9.5) return vec2(135310.0, 14468.0);   // I
  if (c < 10.5) return vec2(270620.0, 6440.0);   // J
  if (c < 11.5) return vec2(103729.0, 17701.0);   // K
  if (c < 12.5) return vec2(33825.0, 31777.0);   // L
  if (c < 13.5) return vec2(710513.0, 17969.0);   // M
  if (c < 14.5) return vec2(708145.0, 17977.0);   // N
  if (c < 15.5) return vec2(575022.0, 14897.0);   // O
  if (c < 16.5) return vec2(509487.0, 17701.0);   // R
  if (c < 17.5) return vec2(459838.0, 15888.0);   // S
  if (c < 18.5) return vec2(135327.0, 4228.0);   // T
  if (c < 19.5) return vec2(575025.0, 14897.0);   // U
  if (c < 20.5) return vec2(575025.0, 4433.0);   // V
  if (c < 21.5) return vec2(714286.0, 14899.0);   // 0
  if (c < 22.5) return vec2(135364.0, 14468.0);   // 1
  if (c < 23.5) return vec2(279086.0, 31812.0);   // 2
  if (c < 24.5) return vec2(266527.0, 14896.0);   // 3
  if (c < 25.5) return vec2(305544.0, 8479.0);   // 4
  if (c < 26.5) return vec2(539711.0, 14896.0);   // 5
  if (c < 27.5) return vec2(492620.0, 14897.0);   // 6
  if (c < 28.5) return vec2(139807.0, 2114.0);   // 7
  if (c < 29.5) return vec2(476718.0, 14897.0);   // 8
  if (c < 30.5) return vec2(1001006.0, 6416.0);   // 9
  if (c < 31.5) return vec2(6336.0, 198.0);   // :
  if (c < 32.5) return vec2(0.0, 6336.0);   // .
  return vec2(0.0);
}
float msgChunk(float m, float k) {             // three characters per float, base 64
  if (m < 0.5) { if (k < 0.5) return 12624.0; return 0.0; }   // REC
  if (m < 1.5) { if (k < 0.5) return 53315.0; return 0.0; }   // CAM
  if (m < 2.5) { if (k < 0.5) return 9425.0; if (k < 1.5) return 12618.0; if (k < 2.5) return 36882.0; if (k < 3.5) return 57668.0; if (k < 4.5) return 25170.0; if (k < 5.5) return 16713.0; return 0.0; }   // SUBJECT IDENTIFIED
  if (m < 3.5) { if (k < 0.5) return 5138.0; if (k < 1.5) return 37571.0; if (k < 2.5) return 462.0; return 0.0; }   // TRACKING
  if (m < 4.5) { if (k < 0.5) return 74701.0; if (k < 1.5) return 58313.0; if (k < 2.5) return 20736.0; if (k < 3.5) return 12626.0; if (k < 4.5) return 16722.0; return 0.0; }   // MOTION DETECTED
  if (m < 5.5) { if (k < 0.5) return 73805.0; if (k < 1.5) return 515.0; if (k < 2.5) return 132958.0; if (k < 3.5) return 28.0; return 0.0; }   // MATCH 98.7
  if (m < 6.5) { if (k < 0.5) return 82508.0; if (k < 1.5) return 5.0; return 0.0; }   // LIVE
  if (m < 7.5) { if (k < 0.5) return 69968.0; if (k < 1.5) return 37906.0; if (k < 2.5) return 21635.0; if (k < 3.5) return 4100.0; if (k < 4.5) return 4432.0; return 0.0; }   // RESTRICTED AREA
  if (m < 8.5) { if (k < 0.5) return 95637.0; if (k < 1.5) return 108120.0; if (k < 2.5) return 120603.0; if (k < 3.5) return 2014.0; return 0.0; }   // 0123456789:
  return 0.0;
}
float msgCount() { return 9.0; }
float msgLen(float m) {
  if (m < 0.5) return 3.0;
  if (m < 1.5) return 3.0;
  if (m < 2.5) return 18.0;
  if (m < 3.5) return 8.0;
  if (m < 4.5) return 15.0;
  if (m < 5.5) return 10.0;
  if (m < 6.5) return 4.0;
  if (m < 7.5) return 15.0;
  if (m < 8.5) return 11.0;
  return 0.0;
}
float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}
float letterIndex(float c) {
  if (abs(c - 1.0) < 0.5) return 0.0;
  if (abs(c - 2.0) < 0.5) return 1.0;
  if (abs(c - 3.0) < 0.5) return 2.0;
  if (abs(c - 4.0) < 0.5) return 3.0;
  if (abs(c - 5.0) < 0.5) return 4.0;
  if (abs(c - 6.0) < 0.5) return 5.0;
  if (abs(c - 7.0) < 0.5) return 6.0;
  if (abs(c - 8.0) < 0.5) return 7.0;
  if (abs(c - 9.0) < 0.5) return 8.0;
  if (abs(c - 10.0) < 0.5) return 9.0;
  if (abs(c - 11.0) < 0.5) return 10.0;
  if (abs(c - 12.0) < 0.5) return 11.0;
  if (abs(c - 13.0) < 0.5) return 12.0;
  if (abs(c - 14.0) < 0.5) return 13.0;
  if (abs(c - 15.0) < 0.5) return 14.0;
  if (abs(c - 16.0) < 0.5) return 17.0;
  if (abs(c - 17.0) < 0.5) return 18.0;
  if (abs(c - 18.0) < 0.5) return 19.0;
  if (abs(c - 19.0) < 0.5) return 20.0;
  if (abs(c - 20.0) < 0.5) return 21.0;
  return -1.0;
}
// </text>

// Heat 0..1 to a thermal-camera ramp.
vec3 thermal(float x) {
  x = clamp(x, 0.0, 1.0);
  if (x < 0.25) return mix(vec3(0.0, 0.0, 0.08), vec3(0.35, 0.0, 0.55), x / 0.25);
  if (x < 0.5) return mix(vec3(0.35, 0.0, 0.55), vec3(0.9, 0.1, 0.2), (x - 0.25) / 0.25);
  if (x < 0.75) return mix(vec3(0.9, 0.1, 0.2), vec3(1.0, 0.6, 0.0), (x - 0.5) / 0.25);
  return mix(vec3(1.0, 0.6, 0.0), vec3(1.0, 1.0, 0.85), (x - 0.75) / 0.25);
}

// A number with a fixed count of digits, at q in font pixels.
float numCov(vec2 q, float v, float digits, float px) {
  float c = 0.0, p10 = 1.0;
  for (int i = 1; i < 6; i++) if (float(i) < digits) p10 *= 10.0;
  for (int i = 0; i < 6; i++) {
    if (float(i) >= digits) break;
    float dgt = mod(floor(v / p10), 10.0);
    c = max(c, charCov(q - vec2(float(i) * 6.0, 0.0), CH_0 + dgt, px));
    p10 /= 10.0;
  }
  return c;
}

vec3 content(vec2 uv) {
  float t = u_beat;
  float k = kick() * p_beat;
  float A = u_aspect;

  // Glitch: some scan lines jump sideways on the kick. Digital zoom punch.
  vec2 suv = uv;
  float gl = floor(uv.y * 48.0);
  if (hash(vec2(gl, floor(t * 4.0))) < p_glitch * k) suv.x += (hash(vec2(gl, 7.0)) - 0.5) * 0.08;
  suv = 0.5 + (suv - 0.5) * (1.0 - 0.03 * k * p_zoom);
  vec2 P = vec2(suv.x * A, suv.y);                        // y down

  // Scene heat: cool wall, a floor with perspective lines, warm walkers.
  float heat = 0.12 + 0.08 * suv.y;
  if (suv.y > 0.55) {
    float fy = (suv.y - 0.55) / 0.45;
    float lx = (suv.x - 0.5) / max(fy, 0.02);
    heat += 0.06 * smoothstep(0.9, 1.0, abs(fract(lx * 4.0) - 0.5) * 2.0) + 0.04 * fy;
  }
  heat += 0.06 * (hash(floor(P * 60.0)) - 0.5);
  float tgt = mod(floor(t / max(p_every, 0.25)), max(1.0, floor(p_people)));
  vec4 box = vec4(-1.0);                                  // centre xy, half size
  for (int i = 0; i < 8; i++) {
    float fi = float(i);
    if (fi >= p_people) break;
    float z = hash(vec2(fi, 3.1));                        // depth: 0 far, 1 near
    float dir = hash(vec2(fi, 8.8)) < 0.5 ? -1.0 : 1.0;
    float sp = (0.4 + hash(vec2(fi, 5.5))) * p_walk * dir / 16.0;
    float x = (fract(hash(vec2(fi, 1.7)) + t * sp) * 1.5 - 0.25) * A;
    float sc = 0.25 + 0.5 * z;
    float feet = 0.58 + 0.38 * z;
    float bob = abs(sin(t * TAU * 0.5 + fi)) * 0.012 * sc;
    vec2 body = vec2(x, feet - 0.42 * sc - bob), head = vec2(x, feet - 0.86 * sc - bob);
    float db = length((P - body) / vec2(0.1 * sc, 0.34 * sc)) - 1.0;
    float dh = length(P - head) / (0.075 * sc) - 1.0;
    float d = min(db, dh);
    float core = 1.0 - smoothstep(-1.0, 0.0, d);           // hotter towards the middle
    float fillp = 1.0 - smoothstep(-0.08, 0.04, d);
    heat = mix(heat, 0.55 + 0.4 * core + 0.05 * hash(floor(P * 90.0)), fillp);
    if (abs(fi - tgt) < 0.5) box = vec4(x, feet - 0.47 * sc, 0.16 * sc, 0.52 * sc);
  }

  vec3 col;
  if (p_palette < 0.5) col = vec3(0.12, 1.0, 0.25) * pow(heat, 1.3) * 1.15;
  else if (p_palette < 1.5) col = thermal(heat);
  else col = vec3(pow(heat, 1.2));
  col += (hash(uv * 571.0 + fract(u_time * 7.0)) - 0.5) * p_grain * 0.3;
  vec3 ui = p_palette < 0.5 ? vec3(0.85, 1.0, 0.85) : vec3(1.0);

  // Targeting box with corner brackets, crosshair and label.
  float px = u_px;
  float w = max(0.0022, px);
  vec2 PU = vec2(uv.x * A, uv.y);
  if (p_boxes > 0.5 && box.x > -0.5) {
    vec2 l = PU - box.xy, hsz = box.zw * (1.0 + 0.12 * (1.0 - smoothstep(0.0, 0.25, fract(t / max(p_every, 0.25)))));
    vec2 dq = abs(l) - hsz;
    float sd = length(max(dq, 0.0)) + min(max(dq.x, dq.y), 0.0);
    float edge = 1.0 - smoothstep(w - px, w + px, abs(sd));
    float corner = abs(l.y) > hsz.y - 3.0 * w ? step(0.55 * hsz.x, abs(l.x)) : step(0.7 * hsz.y, abs(l.y));
    float crossh = (1.0 - smoothstep(w - px, w + px, abs(l.x))) * step(abs(l.y), 0.02)
                + (1.0 - smoothstep(w - px, w + px, abs(l.y))) * step(abs(l.x), 0.02);
    vec3 red = vec3(1.0, 0.2, 0.15);
    col = mix(col, red, clamp(edge * corner + crossh, 0.0, 1.0));
    float s = 0.0036;
    vec2 q = (PU - (box.xy + vec2(-box.z * 1.1, -box.w * 1.1 - 9.0 * s))) / s;
    float tc = textCov(q, floor(p_label + 0.5), px / s);
    col = mix(col, red, tc * step(0.5, fract(t * 2.0) + 0.5));
  }

  // REC, camera number, timestamp.
  float s = 0.005;
  if (p_rec > 0.5) {
    float on = step(u_frac, 0.5);
    float dot0 = 1.0 - smoothstep(0.012 - px, 0.012 + px, length(PU - vec2(0.06, 0.07)));
    col = mix(col, vec3(1.0, 0.1, 0.1), dot0 * on);
    col = mix(col, ui, textCov((PU - vec2(0.085, 0.07 - 3.5 * s)) / s, 0.0, px / s));
  }
  vec2 qc = (PU - vec2(A - 0.06 - 29.0 * s, 0.07 - 3.5 * s)) / s;
  col = mix(col, ui, max(textCov(qc, 1.0, px / s), charCov(qc - vec2(24.0, 0.0), CH_0 + mod(floor(p_cam), 10.0), px / s)));
  if (p_stamp > 0.5) {
    float secs = floor(u_time) + 2.0 * 3600.0 + 13.0 * 60.0;
    vec2 qt = (PU - vec2(0.06, 0.93 - 3.5 * s)) / s;
    float colon = msgChar(8.0, 10.0);
    float c = numCov(qt, mod(floor(secs / 3600.0), 24.0), 2.0, px / s);
    c = max(c, charCov(qt - vec2(12.0, 0.0), colon, px / s));
    c = max(c, numCov(qt - vec2(18.0, 0.0), mod(floor(secs / 60.0), 60.0), 2.0, px / s));
    c = max(c, charCov(qt - vec2(30.0, 0.0), colon, px / s));
    c = max(c, numCov(qt - vec2(36.0, 0.0), mod(secs, 60.0), 2.0, px / s));
    c = max(c, numCov(qt - vec2(56.0, 0.0), mod(floor(t), 10000.0), 4.0, px / s));
    col = mix(col, ui, c);
  }
  // Viewfinder corners.
  vec2 fc = abs(PU - vec2(A * 0.5, 0.5)) - vec2(A * 0.5 - 0.035, 0.465);
  float fe = (1.0 - smoothstep(w - px, w + px, abs(max(fc.x, fc.y)))) * step(max(fc.x, fc.y), w)
           * step(-0.06, min(fc.x, fc.y));
  col = mix(col, ui, fe * 0.8);

  // Scanlines, rolling bar, vignette.
  col *= 1.0 - p_scan * 0.35 * (0.5 + 0.5 * sin(uv.y / u_px * 2.1));
  float rb = fract(uv.y - t * 0.0625 * p_roll);
  col += p_roll * 0.12 * exp(-pow((rb - 0.5) * 7.0, 2.0));
  vec2 vv = uv - 0.5;
  col *= 1.0 - p_vignette * dot(vv, vv) * 1.6;
  return clamp(col * (0.9 + 0.1 * k), 0.0, 1.0);
}
