// Cipher: a wall of code with a message hidden in the middle row that decodes letter by
// letter. Styles: 0 pigpen (the Freemasons' cipher), 1 binary rain, 2 numbers station.
// The decode sweeps across every Period bars; through a BUILD it follows the section, and
// on the DROP the message is fully decoded with a flash. Params are p_* uniforms; ranges
// and defaults are in cipher.json.
//
// @messages: THEY ARE WATCHING|THE EYE SEES ALL|NOVUS ORDO SECLORUM|ANNUIT COEPTIS|WAKE UP|TRUST NO ONE|NOTHING IS WHAT IT SEEMS|WE ARE NOT ALONE|0123456789
uniform float p_style, p_rows, p_speed, p_scramble, p_period, p_msg, p_width, p_glow, p_dim,
              p_hue, p_hue2, p_sat, p_follow, p_beat;

// <text>
// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand.
#define CH_A 1.0
#define CH_C 2.0
#define CH_D 3.0
#define CH_E 4.0
#define CH_G 5.0
#define CH_H 6.0
#define CH_I 7.0
#define CH_K 8.0
#define CH_L 9.0
#define CH_M 10.0
#define CH_N 11.0
#define CH_O 12.0
#define CH_P 13.0
#define CH_R 14.0
#define CH_S 15.0
#define CH_T 16.0
#define CH_U 17.0
#define CH_V 18.0
#define CH_W 19.0
#define CH_Y 20.0
#define CH_0 21.0
#define CH_1 22.0
#define CH_2 23.0
#define CH_3 24.0
#define CH_4 25.0
#define CH_5 26.0
#define CH_6 27.0
#define CH_7 28.0
#define CH_8 29.0
#define CH_9 30.0
vec2 glyph(float c) {
  if (c < 0.5) return vec2(0.0);
  if (c < 1.5) return vec2(1033774.0, 17969.0);   // A
  if (c < 2.5) return vec2(34350.0, 14881.0);   // C
  if (c < 3.5) return vec2(575023.0, 15921.0);   // D
  if (c < 4.5) return vec2(492607.0, 31777.0);   // E
  if (c < 5.5) return vec2(951854.0, 31281.0);   // G
  if (c < 6.5) return vec2(1033777.0, 17969.0);   // H
  if (c < 7.5) return vec2(135310.0, 14468.0);   // I
  if (c < 8.5) return vec2(103729.0, 17701.0);   // K
  if (c < 9.5) return vec2(33825.0, 31777.0);   // L
  if (c < 10.5) return vec2(710513.0, 17969.0);   // M
  if (c < 11.5) return vec2(708145.0, 17977.0);   // N
  if (c < 12.5) return vec2(575022.0, 14897.0);   // O
  if (c < 13.5) return vec2(509487.0, 1057.0);   // P
  if (c < 14.5) return vec2(509487.0, 17701.0);   // R
  if (c < 15.5) return vec2(459838.0, 15888.0);   // S
  if (c < 16.5) return vec2(135327.0, 4228.0);   // T
  if (c < 17.5) return vec2(575025.0, 14897.0);   // U
  if (c < 18.5) return vec2(575025.0, 4433.0);   // V
  if (c < 19.5) return vec2(706097.0, 10933.0);   // W
  if (c < 20.5) return vec2(141873.0, 4228.0);   // Y
  if (c < 21.5) return vec2(714286.0, 14899.0);   // 0
  if (c < 22.5) return vec2(135364.0, 14468.0);   // 1
  if (c < 23.5) return vec2(279086.0, 31812.0);   // 2
  if (c < 24.5) return vec2(266527.0, 14896.0);   // 3
  if (c < 25.5) return vec2(305544.0, 8479.0);   // 4
  if (c < 26.5) return vec2(539711.0, 14896.0);   // 5
  if (c < 27.5) return vec2(492620.0, 14897.0);   // 6
  if (c < 28.5) return vec2(139807.0, 2114.0);   // 7
  if (c < 29.5) return vec2(476718.0, 14897.0);   // 8
  if (c < 30.5) return vec2(1001006.0, 6416.0);   // 9
  return vec2(0.0);
}
float msgChunk(float m, float k) {             // three characters per float, base 64
  if (m < 0.5) { if (k < 0.5) return 16784.0; if (k < 1.5) return 4116.0; if (k < 2.5) return 270.0; if (k < 3.5) return 65619.0; if (k < 4.5) return 29058.0; if (k < 5.5) return 331.0; return 0.0; }   // THEY ARE WATCHING
  if (m < 1.5) { if (k < 0.5) return 16784.0; if (k < 1.5) return 82176.0; if (k < 2.5) return 61444.0; if (k < 3.5) return 61700.0; if (k < 4.5) return 36928.0; if (k < 5.5) return 9.0; return 0.0; }   // THE EYE SEES ALL
  if (m < 2.5) { if (k < 0.5) return 74507.0; if (k < 1.5) return 977.0; if (k < 2.5) return 13196.0; if (k < 3.5) return 61452.0; if (k < 4.5) return 36996.0; if (k < 5.5) return 70540.0; if (k < 6.5) return 10.0; return 0.0; }   // NOVUS ORDO SECLORUM
  if (m < 3.5) { if (k < 0.5) return 45761.0; if (k < 1.5) return 66001.0; if (k < 2.5) return 49280.0; if (k < 3.5) return 66372.0; if (k < 4.5) return 967.0; return 0.0; }   // ANNUIT COEPTIS
  if (m < 4.5) { if (k < 0.5) return 32851.0; if (k < 1.5) return 69636.0; if (k < 2.5) return 13.0; return 0.0; }   // WAKE UP
  if (m < 5.5) { if (k < 0.5) return 70544.0; if (k < 1.5) return 1039.0; if (k < 2.5) return 779.0; if (k < 3.5) return 17100.0; return 0.0; }   // TRUST NO ONE
  if (m < 6.5) { if (k < 0.5) return 66315.0; if (k < 1.5) return 45510.0; if (k < 2.5) return 28677.0; if (k < 3.5) return 77839.0; if (k < 4.5) return 65606.0; if (k < 5.5) return 65984.0; if (k < 6.5) return 17344.0; if (k < 7.5) return 62084.0; return 0.0; }   // NOTHING IS WHAT IT SEEMS
  if (m < 7.5) { if (k < 0.5) return 275.0; if (k < 1.5) return 17281.0; if (k < 2.5) return 49856.0; if (k < 3.5) return 4112.0; if (k < 4.5) return 45833.0; if (k < 5.5) return 4.0; return 0.0; }   // WE ARE NOT ALONE
  if (m < 8.5) { if (k < 0.5) return 95637.0; if (k < 1.5) return 108120.0; if (k < 2.5) return 120603.0; if (k < 3.5) return 30.0; return 0.0; }   // 0123456789
  return 0.0;
}
float msgCount() { return 9.0; }
float msgLen(float m) {
  if (m < 0.5) return 17.0;
  if (m < 1.5) return 16.0;
  if (m < 2.5) return 19.0;
  if (m < 3.5) return 14.0;
  if (m < 4.5) return 7.0;
  if (m < 5.5) return 12.0;
  if (m < 6.5) return 24.0;
  if (m < 7.5) return 16.0;
  if (m < 8.5) return 10.0;
  return 0.0;
}
float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}
float letterIndex(float c) {
  if (abs(c - 1.0) < 0.5) return 0.0;
  if (abs(c - 2.0) < 0.5) return 2.0;
  if (abs(c - 3.0) < 0.5) return 3.0;
  if (abs(c - 4.0) < 0.5) return 4.0;
  if (abs(c - 5.0) < 0.5) return 6.0;
  if (abs(c - 6.0) < 0.5) return 7.0;
  if (abs(c - 7.0) < 0.5) return 8.0;
  if (abs(c - 8.0) < 0.5) return 10.0;
  if (abs(c - 9.0) < 0.5) return 11.0;
  if (abs(c - 10.0) < 0.5) return 12.0;
  if (abs(c - 11.0) < 0.5) return 13.0;
  if (abs(c - 12.0) < 0.5) return 14.0;
  if (abs(c - 13.0) < 0.5) return 15.0;
  if (abs(c - 14.0) < 0.5) return 17.0;
  if (abs(c - 15.0) < 0.5) return 18.0;
  if (abs(c - 16.0) < 0.5) return 19.0;
  if (abs(c - 17.0) < 0.5) return 20.0;
  if (abs(c - 18.0) < 0.5) return 21.0;
  if (abs(c - 19.0) < 0.5) return 22.0;
  if (abs(c - 20.0) < 0.5) return 24.0;
  return -1.0;
}
// </text>

float sdSeg(vec2 p, vec2 a, vec2 b) {
  vec2 pa = p - a, ba = b - a;
  return length(pa - ba * clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0));
}

// Pigpen letter L (0..25) in a unit cell (y down): A-I grid, J-R grid + dot, S-V X, W-Z X + dot.
float pigpen(vec2 q, float L, float w, float px) {
  float d = 1e3;
  float lo = 0.2, hi = 0.8;
  if (L < 17.5) {
    float g = mod(L, 9.0), r = floor(g / 3.0), c = mod(g, 3.0);
    if (r > 0.5) d = min(d, sdSeg(q, vec2(lo, lo), vec2(hi, lo)));
    if (r < 1.5) d = min(d, sdSeg(q, vec2(lo, hi), vec2(hi, hi)));
    if (c > 0.5) d = min(d, sdSeg(q, vec2(lo, lo), vec2(lo, hi)));
    if (c < 1.5) d = min(d, sdSeg(q, vec2(hi, lo), vec2(hi, hi)));
  } else {
    float j = mod(L - 18.0, 4.0);
    vec2 a = j < 0.5 ? vec2(lo, lo) : j < 1.5 ? vec2(lo, lo) : j < 2.5 ? vec2(lo, hi) : vec2(hi, lo);
    vec2 b = j < 0.5 ? vec2(hi, lo) : j < 1.5 ? vec2(lo, hi) : j < 2.5 ? vec2(hi, hi) : vec2(hi, hi);
    vec2 v = j < 0.5 ? vec2(0.5, 0.7) : j < 1.5 ? vec2(0.7, 0.5) : j < 2.5 ? vec2(0.5, 0.3) : vec2(0.3, 0.5);
    d = min(sdSeg(q, a, v), sdSeg(q, v, b));
  }
  float line = 1.0 - smoothstep(w - px, w + px, d);
  bool dot0 = (L > 8.5 && L < 17.5) || L > 21.5;
  if (dot0) line = max(line, 1.0 - smoothstep(0.07 - px, 0.07 + px, length(q - 0.5)));
  return line;
}

vec3 content(vec2 uv) {
  float t = u_beat;
  float k = kick() * p_beat;
  float A = u_aspect;
  bool drop = abs(u_scene - 7.0) < 0.5, build = abs(u_scene - 4.0) < 0.5 || abs(u_scene - 6.0) < 0.5;
  float hueA = p_hue + (p_follow > 0.5 ? u_hue : 0.0);
  vec3 dimc = hsv(hueA, p_sat, 1.0), gold = hsv(p_hue2, p_sat, 1.0);

  float rows = floor(max(3.0, p_rows));
  float ch = 1.0 / rows, cw = ch * 0.8;
  float cols = floor(A / cw);
  vec2 P = vec2(uv.x * A - (A - cols * cw) * 0.5, uv.y);
  vec2 cell = floor(P / vec2(cw, ch));
  vec2 q = fract(P / vec2(cw, ch));
  if (cell.x < 0.0 || cell.x >= cols) return vec3(0.0);
  float pxq = u_px / ch;                                     // one pixel in cell heights

  // The message and how far it has decoded.
  float nMsg = msgCount() - 1.0;                             // the last message is the digits
  float cyc = max(1.0, p_period) * 4.0;
  float m = p_msg < -0.5 ? mod(floor(t / cyc), nMsg) : min(floor(p_msg + 0.5), nMsg - 1.0);
  float L = msgLen(m);
  float ph = fract(t / cyc);
  float front = smoothstep(0.08, 0.6, ph) * (L + 2.0) - 1.0;
  if (ph > 0.93) front = -1.0;
  if (build) front = u_sp * (L + 2.0) - 1.0;
  float flash = 0.0;
  if (drop) { front = L + 1.0; flash = exp(-u_since * 0.7); }
  float mrow = floor(rows * 0.5);
  float mcol = floor((cols - L) * 0.5);
  bool inMsg = cell.y == mrow && cell.x >= mcol && cell.x < mcol + L;
  float idx = cell.x - mcol;
  float code = inMsg ? msgChar(m, idx) : 0.0;
  bool decoded = inMsg && idx < front;
  float atFront = inMsg ? exp(-abs(idx - front) * 1.5) : 0.0;

  // The symbol in this cell: scrambling, unless it's part of the message.
  float tick = floor(t * p_scramble + hash(cell) * 4.0);
  float rnd = hash(cell + tick * 0.37);
  float s = ch * 0.62 / 7.0;
  vec2 fq = (q * vec2(cw, ch) - vec2(cw - 5.0 * s, ch - 7.0 * s) * 0.5) / s;   // font pixels, centred
  float fpx = u_px / s;
  float w = p_width;
  float ink = 0.0, bright = p_dim;

  if (decoded) {
    ink = code > 0.5 ? charCov(fq, code, fpx) : 0.0;
  } else if (p_style < 0.5) {
    float li = inMsg ? letterIndex(code) : floor(rnd * 26.0);
    ink = li < -0.5 ? 0.0 : pigpen(q * vec2(0.8, 1.0) + vec2(0.1, 0.0), li, w, pxq);
    if (!inMsg) bright *= step(0.35, hash(cell + 0.5));
  } else if (p_style < 1.5) {
    float sp = (0.5 + hash(vec2(cell.x, 4.4))) * p_speed;
    float trail = 6.0 + 10.0 * hash(vec2(cell.x, 2.2));
    float head = fract(t * sp / 8.0 + hash(vec2(cell.x, 1.1))) * (rows + trail);
    float dd = head - cell.y;
    float rain = dd > 0.0 && dd < trail ? pow(1.0 - dd / trail, 1.5) : 0.0;
    float bit = step(0.5, rnd);
    ink = charCov(fq, CH_0 + bit, fpx);
    bright *= inMsg ? 1.0 : rain * 2.5 + (dd > 0.0 && dd < 1.0 ? 3.0 : 0.0);
  } else {
    float gx = mod(cell.x, 6.0);
    float dg = floor(hash(cell + floor(t / 4.0) * 0.71) * 10.0);
    ink = gx > 4.5 || (!inMsg && hash(vec2(cell.y, 9.0)) < 0.25) ? 0.0 : charCov(fq, CH_0 + dg, fpx);
  }

  vec3 col = dimc * ink * bright * (inMsg ? 1.6 : 1.0);
  if (decoded) col = gold * ink * (1.2 + 0.8 * k + flash);
  col += vec3(1.0) * ink * atFront * 1.2;
  if (inMsg) col += gold * p_glow * 0.15 * (decoded ? 1.0 : 0.3);
  col += gold * flash * 0.15;
  return (1.0 - exp(-col * 1.3)) * (0.85 + 0.15 * k);
}
