// Hypnotoad: ALL GLORY TO THE HYPNOTOAD. Front-on and symmetrical, which is how he is seen and
// the most hypnotic way to put anything on a wall.
//
// He keeps his own colours whatever the show's hue is doing: olive and cream, and two bulging
// yellow eyeballs. Tint overrules that. Everything behind him -- hypno rings radiating from his
// stare, and sacred geometry over them -- takes the hue, on a small quantised palette.
//
// The eyes are the whole point, built to the show's animation: plain yellow eyeballs, and in each
// a big soft black pupil snapping between a slit, a bean, an arch and a four-lobed star, the two
// eyes out of step, ringed by a glowing border that is offset contours of the pupil itself. The
// shapes step on the beat grid; the kick pops the pupil and makes the eyeballs glow.
//
// Drivers (docs/reactive.md): A Hit -> the bob and squash, the pupil throb and the eye glow;
// B Move -> the geometry turning, the rings crawling and the pupil outline wobbling; C Change -> the palette and
// how much sacred line-work is on top.
// Params are p_* uniforms; ranges and defaults are in hypnotoad.json.
//
// @messages: ALL GLORY TO|THE HYPNOTOAD
uniform float p_size, p_bob, p_blink, p_patches, p_tint, p_collar, p_ink, p_halo,
              p_eyesize, p_pupil, p_pstep, p_glide, p_border, p_irisc, p_glory,
              p_mode, p_scale, p_detail, p_width, p_spin,
              p_bands, p_wave, p_bandspin, p_glow,
              p_aband, p_aloop, p_ashape, p_aamt,
              p_bband, p_bloop, p_bshape, p_bamt,
              p_cband, p_cloop, p_cshape, p_camt,
              p_hue, p_palette, p_sat, p_follow;

// <text>
// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand.
#define CH_A 1.0
#define CH_D 2.0
#define CH_E 3.0
#define CH_G 4.0
#define CH_H 5.0
#define CH_L 6.0
#define CH_N 7.0
#define CH_O 8.0
#define CH_P 9.0
#define CH_R 10.0
#define CH_T 11.0
#define CH_Y 12.0
vec2 glyph(float c) {
  if (c < 0.5) return vec2(0.0);
  if (c < 1.5) return vec2(1033774.0, 17969.0);   // A
  if (c < 2.5) return vec2(575023.0, 15921.0);   // D
  if (c < 3.5) return vec2(492607.0, 31777.0);   // E
  if (c < 4.5) return vec2(951854.0, 31281.0);   // G
  if (c < 5.5) return vec2(1033777.0, 17969.0);   // H
  if (c < 6.5) return vec2(33825.0, 31777.0);   // L
  if (c < 7.5) return vec2(708145.0, 17977.0);   // N
  if (c < 8.5) return vec2(575022.0, 14897.0);   // O
  if (c < 9.5) return vec2(509487.0, 1057.0);   // P
  if (c < 10.5) return vec2(509487.0, 17701.0);   // R
  if (c < 11.5) return vec2(135327.0, 4228.0);   // T
  if (c < 12.5) return vec2(141873.0, 4228.0);   // Y
  return vec2(0.0);
}
float msgChunk(float m, float k) {             // three characters per float, base 64
  if (m < 0.5) { if (k < 0.5) return 24961.0; if (k < 1.5) return 24832.0; if (k < 2.5) return 49800.0; if (k < 3.5) return 33472.0; return 0.0; }   // ALL GLORY TO
  if (m < 1.5) { if (k < 0.5) return 12619.0; if (k < 1.5) return 49472.0; if (k < 2.5) return 33225.0; if (k < 3.5) return 4619.0; if (k < 4.5) return 2.0; return 0.0; }   // THE HYPNOTOAD
  return 0.0;
}
float msgCount() { return 2.0; }
float msgLen(float m) {
  if (m < 0.5) return 12.0;
  if (m < 1.5) return 13.0;
  return 0.0;
}
float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}
float letterIndex(float c) {
  if (abs(c - 1.0) < 0.5) return 0.0;
  if (abs(c - 2.0) < 0.5) return 3.0;
  if (abs(c - 3.0) < 0.5) return 4.0;
  if (abs(c - 4.0) < 0.5) return 6.0;
  if (abs(c - 5.0) < 0.5) return 7.0;
  if (abs(c - 6.0) < 0.5) return 11.0;
  if (abs(c - 7.0) < 0.5) return 13.0;
  if (abs(c - 8.0) < 0.5) return 14.0;
  if (abs(c - 9.0) < 0.5) return 15.0;
  if (abs(c - 10.0) < 0.5) return 17.0;
  if (abs(c - 11.0) < 0.5) return 19.0;
  if (abs(c - 12.0) < 0.5) return 24.0;
  return -1.0;
}
// </text>

#define TAU 6.2831853
#define PI  3.14159265

// Painted shape over shape: a fill and the ink laid over it. gS carries a distance in the toad's
// own units out to surface units, so the line stays one width whatever size he is drawn at.
vec3 gCol;
float gInk, gPx, gLw, gS, gH;

const vec3 INK   = vec3(0.14, 0.10, 0.03);   // the cartoon's near-black brown line
const vec3 HIDE  = vec3(0.50, 0.42, 0.14);   // his olive khaki
const vec3 HIDE2 = vec3(0.60, 0.51, 0.19);   // the lighter olive across the top of him
const vec3 DARK  = vec3(0.34, 0.28, 0.08);   // the blotches over his back
const vec3 DARK2 = vec3(0.24, 0.19, 0.05);   // deepest: the wart ticks
const vec3 CREAM = vec3(0.82, 0.79, 0.60);   // throat and belly
const vec3 CREAM2 = vec3(0.70, 0.67, 0.49);  // under the belly
const vec3 SCLER = vec3(1.00, 0.90, 0.26);   // the eyeball yellow
const vec3 SCLD  = vec3(0.78, 0.55, 0.08);   // the same yellow turning away from the light
const vec3 COLL  = vec3(0.42, 0.29, 0.35);   // the mauve collar
const vec3 MINT  = vec3(0.66, 0.87, 0.82);   // its buckle and the tag

mat2 rot(float a) { float c = cos(a), s = sin(a); return mat2(c, s, -s, c); }
float sdSeg(vec2 p, vec2 a, vec2 b) {
  vec2 pa = p - a, ba = b - a;
  return length(pa - ba * clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0));
}
float sdEll(vec2 p, vec2 r) { return (length(p / r) - 1.0) * min(r.x, r.y); }

// A circle pulled gently out of shape: the patches on his back, because nothing about him is
// drawn with a compass.
float blob(vec2 p, float r, float wob, float ph) {
  float l = length(p);
  if (l > r * 1.8 + 0.02) return l - r * 1.4;     // far off: skip the trig
  float a = atan(p.y, p.x);
  return l - r * (1.0 + wob * (0.34 * sin(a * 3.0 + ph) + 0.22 * sin(a * 2.0 - ph * 0.7)));
}
// The little "c" ticks the cartoon scatters over his back: a thin arc, cut in half, rotated.
float wart(vec2 p, vec2 at, float r, float a) {
  float l = length(p - at);
  if (l > r + 0.03) return l - r - 0.005;
  vec2 d = rot(a) * (p - at);
  return max(abs(length(d) - r) - 0.005, -d.x);
}

void draw(float d, vec3 c) {
  float f = 1.0 - smoothstep(-gPx, gPx, d);
  gCol = mix(gCol, c, f);
  if (gLw > 0.0) {
    float e = 1.0 - smoothstep(gLw - gPx, gLw + gPx, abs(d));
    gInk = max(gInk * (1.0 - f), e);
  } else {
    gInk *= 1.0 - f;
  }
}
// Rounded union, so head, body and haunches read as one animal rather than shapes stacked up.
float smin(float a, float b, float k) {
  float h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
  return mix(b, a, h) - k * h * (1.0 - h);
}
void D(float d, vec3 c) { draw(d * gS, c); }
// A fill with no outline, for shading inside a shape that is already outlined.
void shade(float d, vec3 c, float amt) {
  gCol = mix(gCol, c, (1.0 - smoothstep(-gPx, gPx, d * gS)) * amt);
}

// ---------------------------------------------------------------- the eyes
// Built to the show's own animation. The eyeball is plain yellow; the picture is the pupil, a
// big soft black blob that snaps from shape to shape -- a flat slit, a wide bean, a frowning
// arch, a squat four-lobed star -- with the two eyes out of step. Round it runs a thin glowing
// border made of offset contours of the pupil itself (dark red, bright red, orange, then a
// yellow bloom), so when the pupil warps the border warps with it. The eyeball throbs between
// a bright glowing yellow and a dull olive-yellow.

float capX(vec2 p, float L, float r) { p.x = max(abs(p.x) - L, 0.0); return length(p) - r; }

// Pupil shape k (0 slit, 1 bean, 2 arch, 3 star) at p, in units of the eye's radius.
float pupilShape(vec2 p, float k) {
  if (k < 0.5) return capX(p, 0.46, 0.125);
  if (k < 1.5) { p.y -= 0.04 * (1.0 - p.x * p.x / 0.36); return (length(p / vec2(0.62, 0.25)) - 1.0) * 0.25; }
  if (k < 2.5) {                                           // the arch: a boomerang bent upward
    p.y -= 0.10 - 0.30 * p.x * p.x;
    return capX(p, 0.42, 0.155) * 0.88;
  }
  vec2 s = p / vec2(1.0, 0.82);                            // the star: a squat, chunky plus
  float l = max(length(s), 1e-4);
  float c2 = (s.x * s.x - s.y * s.y) / (l * l);            // cos 2a, and cos 4a from it: no atan
  return (l - 0.47 * (0.87 + 0.13 * (2.0 * c2 * c2 - 1.0) + 0.04 * s.y / l)) * 0.82;
}
// The show's own sequences, one step each: the left eye and the right run different ones.
float seqShape(float n, float side) {
  float i = mod(n, 8.0);
  side = mod(side + floor(n / 8.0), 2.0);                  // every other cycle they swap
  if (side < 0.5) return i < 0.5 ? 3.0 : i < 1.5 ? 0.0 : i < 2.5 ? 1.0 : i < 3.5 ? 3.0
                       : i < 5.5 ? 0.0 : i < 6.5 ? 1.0 : 2.0;
  return i < 0.5 ? 2.0 : i < 1.5 ? 0.0 : i < 2.5 ? 1.0 : i < 3.5 ? 2.0
       : i < 4.5 ? 3.0 : i < 6.5 ? 0.0 : 2.0;
}
// Border colour, band b (0 dark red, 1 red, 2 orange, 3 bloom).
vec3 borderCol(float b, float t) {
  if (p_irisc < 0.5)
    return b < 0.5 ? vec3(0.40, 0.02, 0.02) : b < 1.5 ? vec3(0.95, 0.10, 0.03)
         : b < 2.5 ? vec3(1.00, 0.50, 0.04) : vec3(1.00, 1.00, 0.70);
  if (p_irisc < 1.5) return hsv(fract(t * 0.125 + b * 0.16), b > 2.5 ? 0.35 : 0.9, b < 0.5 ? 0.5 : 1.0);
  return hsv(fract(gH + b * 0.05), (b > 2.5 ? 0.3 : 0.9) * p_sat, b < 0.5 ? 0.45 : 1.0);
}

// A: the hit (throb and brightness). B: the move (the outline wobbling). side: 0 left, 1 right.
void eye(vec2 q, vec2 at, float R, float t, float A, float B, float shut, float side) {
  vec2 e = q - at;
  float r = length(e);
  if (r > R * 1.06 + 0.02) return;
  D(r - R, SCLER);
  if (r < R + 0.02) {
    float inside = 1.0 - smoothstep(-gPx, gPx, (r - R) * gS);
    // Which shape, and how far into the glide to the next one.
    float st = p_pstep < 0.5 ? 0.25 : p_pstep < 1.5 ? 0.5 : 1.0;
    float n = floor(t / st), f = fract(t / st);
    float g = clamp(p_glide, 0.0, 1.0);
    float m = g > 0.001 ? smoothstep(1.0 - g, 1.0, f) : 0.0;
    // The glow throbs: bright on the kick, dull between, with the cartoon's own flicker.
    float P = clamp(0.08 + 2.2 * A + 0.30 * step(0.5, hash(vec2(n, 7.0 + side))), 0.0, 1.0);

    vec2 u = e / R;
    u /= (p_pupil / 0.62) * (1.0 + 0.08 * A);              // the throb: a quick pop on the hit
    float d = pupilShape(u, seqShape(n, side));
    if (m > 0.0) d = mix(d, pupilShape(u, seqShape(n + 1.0, side)), m);
    if (B > 0.01) {                                        // sin(2a + phase), without atan
      float l2 = max(dot(u, u), 1e-6), ph = t * TAU + side * 2.0;
      d += B * 0.02 * (2.0 * u.x * u.y * cos(ph) + (u.x * u.x - u.y * u.y) * sin(ph)) / l2;
    }
    d *= (p_pupil / 0.62) * (1.0 + 0.08 * A);              // back to eye units

    // The eyeball, dull olive-yellow to glowing, with a little roundness at the lower right.
    vec3 ball = mix(vec3(0.72, 0.67, 0.14), vec3(1.0, 0.94, 0.18), P);
    float sh = smoothstep(0.6, 1.1, length(u * (p_pupil / 0.62) - vec2(-0.2, 0.25)));
    ball *= 1.0 - 0.22 * sh;
    // The border, from the outside in: bloom, orange, red, dark red, black.
    float bw = p_border * mix(1.15, 0.75, P);
    float aa = gPx / max(gS * R, 1e-5) * 1.5;
    vec3 c = mix(ball, borderCol(3.0, t), exp(-max(d - 0.12 * bw, 0.0) / (0.05 + 0.32 * P)) * (0.10 + 0.90 * P));
    c = mix(c, borderCol(2.0, t), 1.0 - smoothstep(0.125 * bw - aa, 0.125 * bw + aa, d));
    c = mix(c, borderCol(1.0, t), 1.0 - smoothstep(0.095 * bw - aa, 0.095 * bw + aa, d));
    c = mix(c, borderCol(0.0, t), 1.0 - smoothstep(0.045 * bw - aa, 0.045 * bw + aa, d));
    c = mix(c, vec3(0.02, 0.012, 0.005), 1.0 - smoothstep(-aa, aa, d));
    gCol = mix(gCol, c, inside);
    // A faint glint, kept subtle: the show has none.
    shade(sdEll(rot(-0.6) * (e - R * vec2(-0.40, 0.52)), R * vec2(0.15, 0.08)), vec3(1.0), 0.40);
  }
  // The blink: an olive lid sweeping down over the dome.
  if (shut > 0.01) {
    float ly = R * (1.05 - 2.15 * shut) - 0.22 * R * shut * (1.0 - e.x * e.x / (R * R));
    D(max(r - R * 1.02, ly - e.y), HIDE);
  }
  // The lower lid: a fold of his skin cupping the bottom of the dome, which is what makes the
  // eye bulge out of the head rather than sit on it.
  D(max(r - R * 1.04, e.y + R * 0.80 - 0.28 * e.x * e.x / R), HIDE);
}

// ---------------------------------------------------------------- him
void toad(vec2 q, float t, float A, float B) {
  float bl = p_blink * step(0.88, hash(vec2(floor(t * 0.5), 3.0)));
  float shut = bl * max(0.0, 1.0 - abs(fract(t * 0.5) - 0.12) * 9.0);
  float R = 0.170 * p_eyesize;
  float ex = 0.190 + 0.05 * (p_eyesize - 1.0);
  float ey = 0.305 + 0.10 * (p_eyesize - 1.0);      // bigger eyes sit higher, clear of the nostrils
  vec2 L = vec2(-ex, ey), Rr = vec2(ex, ey);

  // His hind feet, behind him: long thin toes splayed out wide past the haunches.
  bool low = q.y < -0.26;
  if (low) for (int s2 = 0; s2 < 2; s2++) {
    float sg = float(s2) * 2.0 - 1.0;
    vec2 an = vec2(sg * 0.430, -0.360);
    for (int i = 0; i < 3; i++) {
      float a = mix(0.95, 1.70, float(i) / 2.0);
      vec2 tip = an + vec2(sg * sin(a), -cos(a)) * 0.150;
      D(sdSeg(q, an, tip) - 0.020, HIDE);
      D(length(q - tip) - 0.026, HIDE);
    }
  }

  // One squat mass: the haunches, body, head and eye sockets blended so the line runs right
  // round the lot of him.
  float haunch = smin(sdEll(q - vec2(-0.385, -0.215), vec2(0.135, 0.165)),
                      sdEll(q - vec2( 0.385, -0.215), vec2(0.135, 0.165)), 0.04);
  float body = smin(sdEll(q - vec2(0.0, -0.150), vec2(0.405, 0.265)),
                    sdEll(q - vec2(0.0, 0.110), vec2(0.285, 0.205)), 0.15);
  body = smin(body, haunch, 0.10);
  body = smin(body, length(q - L) - R * 0.97, 0.10);
  body = smin(body, length(q - Rr) - R * 0.97, 0.10);
  D(body, HIDE);
  shade(sdEll(q - vec2(0.0, 0.190), vec2(0.270, 0.180)), HIDE2, 0.85);   // lighter over the top
  shade(haunch + 0.02, DARK, 0.30);                                      // shadow on the haunches

  // Blotches over his back and haunches, with the little "c" ticks on them.
  if (p_patches > 0.01 && body < 0.02) {
    float k = p_patches;
    D(blob(q - vec2(-0.330, -0.010), 0.048 * k, 0.25, 1.1), DARK);
    D(blob(q - vec2( 0.335, -0.035), 0.042 * k, 0.25, 2.3), DARK);
    D(blob(q - vec2(-0.415, -0.140), 0.050 * k, 0.25, 1.9), DARK);
    D(blob(q - vec2( 0.420, -0.170), 0.046 * k, 0.25, 0.8), DARK);
    D(blob(q - vec2(-0.110, 0.205), 0.032 * k, 0.25, 0.4), DARK);
    D(blob(q - vec2( 0.125, 0.190), 0.026 * k, 0.25, 3.1), DARK);
    gLw *= 0.55;                                    // the ticks are drawn with a finer nib
    D(wart(q, vec2(-0.300, -0.105), 0.016, 0.6), DARK2);
    D(wart(q, vec2( 0.305, -0.125), 0.015, 2.4), DARK2);
    D(wart(q, vec2(-0.395, -0.270), 0.015, 1.4), DARK2);
    D(wart(q, vec2( 0.410, -0.265), 0.015, 3.6), DARK2);
    gLw /= 0.55;
  }

  // The mouth: one wide, stern line nearly the full width of his head, sagging a touch in the
  // middle and turning down at the corners. Above it the olive upper lip and jaw; below it the
  // pale throat, which starts in the lip's shadow.
  float ax = abs(q.x);
  float ym = 0.092 - 0.030 * (ax / 0.28) * (ax / 0.28) - 0.034 * smoothstep(0.17, 0.30, ax);
  float mouth = q.y - ym;
  // Throat and belly: pale khaki, wide right up under the jaw.
  float belly = smin(sdEll(q - vec2(0.0, -0.185), vec2(0.300, 0.240)),
                     sdEll(q - vec2(0.0, 0.000), vec2(0.330, 0.140)), 0.06);
  belly = max(belly, mouth + 0.006);
  D(belly, CREAM);
  gCol = mix(gCol, CREAM2, (1.0 - smoothstep(-gPx, gPx, belly * gS))
             * smoothstep(-0.20, -0.38, q.y) * 0.55);     // soft shading low in the belly
  float lw0 = gLw;

  // His hands, flat on the ground in front of him, with long fingers ending in pads.
  if (low) for (int s2 = 0; s2 < 2; s2++) {
    float sg = float(s2) * 2.0 - 1.0;
    vec2 an = vec2(sg * 0.275, -0.370);
    for (int i = 0; i < 4; i++) {
      float a = mix(-0.30, 1.15, float(i) / 3.0);
      vec2 tip = an + vec2(sg * sin(a), -cos(a)) * 0.135;
      D(sdSeg(q, an, tip) - 0.016, HIDE);
      D(length(q - tip) - 0.021, HIDE);
    }
    D(sdEll(q - an - vec2(0.0, 0.012), vec2(0.062, 0.042)), HIDE);
  }

  // The collar: a mauve band wrapped round the neck, from one edge of him to the other. It sags
  // at the front the way a band round something round does, and its ends rise and tuck up under
  // the jaw at the sides, where the upper lip overhangs it. It darkens as it turns
  // away at the sides, casts a thin shadow below itself and is clipped to his outline, so it can
  // never stick out past him whatever size he is or however he squashes.
  if (p_collar > 0.01 && q.y > -0.21 && q.y < 0.08 && ax < 0.45) {
    float cw = 0.022 * p_collar;
    float cy = q.y + 0.040 - 0.060 * (ax / 0.33) * (ax / 0.33);
    float band = max(max(abs(cy) - cw, body + 0.001), mouth + 0.004);
    shade(max(max(abs(cy + cw + 0.007) - 0.008, body), mouth), INK, 0.30);        // its shadow underneath
    D(band, COLL);
    float turn = smoothstep(0.08, 0.32, ax);
    shade(band, COLL * 0.6, 0.6 * turn);                                // turning away
    shade(max(abs(cy - cw * 0.55) - cw * 0.22, band), vec3(0.62, 0.47, 0.55), 0.7 * (1.0 - turn));
    gLw *= 0.6;
    vec2 qa = vec2(ax, q.y);
    for (int i = 0; i < 4; i++) {                        // the stitch holes along the band
      float sx = 0.075 + float(i) * 0.055;
      float sy = -0.040 + 0.060 * (sx / 0.33) * (sx / 0.33);
      D(length(qa - vec2(sx, sy)) - 0.0050 * (1.0 - 0.4 * turn), INK);
    }
    gLw /= 0.6;
    D(sdEll(q - vec2(0.0, -0.040), vec2(0.032, 0.026)), MINT);      // buckle, front centre
    D(sdEll(q - vec2(0.0, -0.040), vec2(0.014, 0.010)), COLL);
    D(sdSeg(q, vec2(0.0, -0.064), vec2(0.0, -0.100)) - 0.007, MINT);
    D(sdEll(q - vec2(0.0, -0.138), vec2(0.036, 0.040)), MINT);     // tag
  }

  // The upper lip overhangs the throat and the collar: its shadow falls just under the line,
  // and the lip itself catches the light as it rolls over.
  shade(max(max(mouth, -(mouth + 0.040)), body + 0.004), INK, 0.30 * smoothstep(0.040, 0.0, -mouth));
  shade(max(max(-mouth, mouth - 0.035), body + 0.01), HIDE2, 0.55 * smoothstep(0.035, 0.0, mouth));

  // The mouth line itself, over everything below it: heavy in the middle, tapering to the
  // corners, and ending just inside his outline.
  {
    float slope = -0.060 * ax / (0.28 * 0.28) - 0.034 * 6.0 * smoothstep(0.17, 0.30, ax) * (1.0 - smoothstep(0.17, 0.30, ax)) / 0.13;
    float md = abs(mouth) / sqrt(1.0 + slope * slope);
    float mw = max(max(gLw, u_px * 1.2) * 1.5 / gS, 0.005) * (1.0 - 0.55 * smoothstep(0.12, 0.30, ax));
    float mc = max(md - mw, body + 0.010);
    gCol = mix(gCol, INK, 1.0 - smoothstep(-gPx, gPx, mc * gS));
    gInk *= smoothstep(-gPx, gPx, mc * gS);
  }

  // Nostrils, and the two little brow curls on the top of his head.
  D(sdEll(q - vec2(-0.045, 0.150), vec2(0.011, 0.015)), INK);
  D(sdEll(q - vec2( 0.045, 0.150), vec2(0.011, 0.015)), INK);
  gLw *= 0.6;
  D(wart(q, vec2(-0.070, 0.395), 0.026, -0.5), INK);
  D(wart(q, vec2( 0.070, 0.395), 0.026, 3.6), INK);
  gLw = lw0;

  // And the eyes, on top of everything.
  eye(q, L, R, t, A, B, shut, 0.0);
  eye(q, Rr, R, t, A, B, shut, 1.0);
}

// ---------------------------------------------------------------- the picture
vec3 content(vec2 uv) {
  float A = drive(p_aband, p_aloop, p_ashape, p_aamt);   // Hit    -> bob, iris pulse, glow
  float B = drive(p_bband, p_bloop, p_bshape, p_bamt);   // Move   -> geometry and ring crawl
  float C = drive(p_cband, p_cloop, p_cshape, p_camt);   // Change -> palette and line-work

  float bb = barBeat(), t = u_beat;
  float H = p_hue + (p_follow > 0.5 ? u_hue : 0.0) + 0.11 * C;
  gH = H;
  float PAL = max(2.0, floor(p_palette + 0.5));

  vec2 p = (uv - 0.5) * vec2(u_aspect, 1.0);
  p.y = -p.y;

  gPx = u_px * 0.8;
  gLw = p_ink > 0.004 ? max(p_ink * 0.0042, u_px * 1.1) : 0.0;
  gInk = 0.0;

  // Where he sits. His art runs from about -0.50 (toes) to +0.47 (top of the eyes); with the
  // caption on he shrinks and the words take the top and bottom of the frame.
  float cap = p_glory > 0.5 ? 1.0 : 0.0;
  float Sz = p_size * 0.66 * mix(1.0, 0.84, cap) * min(1.0, u_aspect * 0.95);
  // Drawn big he is cropped at the feet, never at the eyes: the top of his highest hop stays
  // inside the frame (or clear of the caption).
  float y0 = min(0.01 - 0.01 * cap,
                 mix(0.485, 0.345, cap) - (0.31 + 0.10 * (p_eyesize - 1.0) + 0.172 * p_eyesize + p_bob * 0.13) * Sz);
  vec2 eyeC = vec2(0.0, y0 + 0.30 * Sz);

  // ---- the hypno rings: wavy concentric bands pouring out of his stare, on a small quantised
  // palette so they read as drawn rather than as a rainbow gradient.
  vec2 pr = p - eyeC;
  float r = length(pr), a = atan(pr.y, pr.x);
  float NB = max(1.0, p_bands);
  float wob = p_wave * (1.0 + 0.6 * B) * smoothstep(0.0, 0.35, r) * (0.09 * sin(a * 7.0 + t * 0.35) + 0.05 * sin(a * 11.0 - t * 0.2));
  float ph = r * NB - t * p_bandspin + wob * NB;
  float bandI = floor(ph), bfr = fract(ph);
  float bw = u_px * NB * 1.5;
  float bnb = bfr > 0.5 ? bandI + 1.0 : bandI - 1.0;
  vec3 c0 = hsv(fract(H + mod(bandI, PAL) / PAL * 0.16), 0.90 * p_sat, mix(0.10, 1.0, mod(bandI, 2.0)));
  vec3 c1 = hsv(fract(H + mod(bnb, PAL) / PAL * 0.16), 0.90 * p_sat, mix(0.10, 1.0, mod(bnb, 2.0)));
  vec3 bg = mix(c0, c1, 0.5 - 0.5 * smoothstep(0.0, bw, min(bfr, 1.0 - bfr)));
  gCol = bg * (0.50 + 0.40 * p_glow);
  // A glow coming off him, so he sits in the middle of it rather than on top of it.
  gCol += hsv(fract(H + 0.06), 0.7 * p_sat, 1.0) * exp(-length(p) * 3.0) * 0.28 * (0.5 + 0.6 * C) * p_glow;

  // ---- sacred geometry over the bands, in a thin bright line
  float gd = 1e9;
  if (p_width > 0.01) {
    float S = max(0.04, p_scale);
    float N = max(1.0, floor(p_detail + 0.5));
    vec2 gp = rot(t * p_spin * TAU + B * 0.6) * p;
    if (p_mode < 0.5) {
      // Flower of Life: circles of radius S on a hex lattice of the same spacing.
      float jj = gp.y / (S * 0.866025), ii = gp.x / S - 0.5 * jj;
      vec2 base = floor(vec2(ii, jj));
      float lim = (N - 0.5) * (N - 0.5) * S * S;
      for (int i = -1; i <= 2; i++) for (int j = -1; j <= 2; j++) {
        vec2 ij = base + vec2(float(i), float(j));
        vec2 c = vec2((ij.x + 0.5 * ij.y) * S, ij.y * 0.866025 * S);
        gd = min(gd, dot(c, c) > lim ? 1e9 : abs(length(gp - c) - S));
      }
      gd = min(gd, abs(length(gp) - (N + 0.5) * S));
    } else if (p_mode < 1.5) {
      // Metatron's Cube: thirteen circles and the 78 lines between their centres. It has the
      // symmetry of a hexagon, so fold the plane into one twelfth of it: the circles and the pieces
      // of line that cross that wedge (eleven, worked out once) draw the whole figure.
      float rr = S * 0.62;
      float ga = mod(atan(gp.y, gp.x), PI / 3.0);
      ga = min(ga, PI / 3.0 - ga);
      gp = length(gp) * vec2(cos(ga), sin(ga));
      gd = min(abs(length(gp) - rr), abs(length(gp - vec2(1.7321, 1.0) * rr) - rr));
      gd = min(gd, abs(length(gp - vec2(3.4641, 2.0) * rr) - rr));
      gd = min(gd, sdSeg(gp, vec2(0.0000, 0.0000) * rr, vec2(3.4641, 2.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(1.1547, 0.0000) * rr, vec2(1.7321, 1.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(1.7321, 0.0000) * rr, vec2(1.7321, 1.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(1.3856, 0.0000) * rr, vec2(1.7321, 1.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(1.7321, 1.0000) * rr, vec2(2.3094, 0.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(0.8660, 0.5000) * rr, vec2(1.1547, 0.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(1.1547, 0.6667) * rr, vec2(1.7320, 0.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(1.7320, 0.0000) * rr, vec2(3.4641, 2.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(2.3094, 0.0000) * rr, vec2(3.4641, 2.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(1.1547, 0.6667) * rr, vec2(1.3856, 0.0000) * rr));
      gd = min(gd, sdSeg(gp, vec2(3.4641, 0.0000) * rr, vec2(3.4641, 2.0000) * rr));
    } else {
      // A mandala: concentric rings crossed by spokes.
      float ga = atan(gp.y, gp.x), gr = length(gp);
      gd = min(abs(fract(gr / S) - 0.5) * S * 2.0,
               abs(fract(ga * N / TAU + 0.5) - 0.5) * TAU / N * max(gr, 0.02));
      gd = min(gd, abs(gr - S * (N + 0.5)));
    }
  }
  float lw = p_width * (0.0014 + 0.8 * u_px);
  float line = (1.0 - smoothstep(lw, lw + 1.4 * u_px, gd)) + 0.30 * exp(-gd / (lw * 4.0 + 0.004));
  // Kept off him: it is there to frame him, not to be drawn across his face.
  float hs = sdEll(p - vec2(0.0, y0 - 0.03 * Sz), vec2(0.58 * Sz, 0.55 * Sz));
  line *= (0.35 + 0.55 * C) * mix(0.35, 1.0, smoothstep(-0.05 * Sz, 0.12 * Sz, hs)) * step(0.01, p_width);
  gCol = mix(gCol, hsv(fract(H + 0.10), 0.22 * p_sat, 1.0), clamp(line, 0.0, 1.0));

  // ---- him, bobbing
  float wobl = sin(TAU * (bb / max(loopBeats(p_aloop), 0.5)));
  float up = max(0.0, wobl), down = max(0.0, -wobl);
  float hop = p_bob * (0.030 + 0.10 * A) * up;
  float squash = 1.0 + p_bob * (0.04 + 0.18 * A) * down;

  gS = max(Sz, 1e-4);
  vec2 c = (p - vec2(0.0, y0 + hop * Sz)) / Sz;
  // Squash on the landing, pivoting on his feet; he is a toad, he does not stretch upward.
  c.x /= squash;
  c.y = (c.y + 0.5) * squash - 0.5;
  c = rot(p_bob * 0.045 * sin(TAU * (bb / max(loopBeats(p_aloop), 0.5) * 0.5))) * (c + vec2(0.0, 0.5)) - vec2(0.0, 0.5);

  // A soft shadow roughly his shape, darkening the rings, so he reads off them.
  if (p_halo > 0.004) {
    float hh = sdEll(p - vec2(0.0, y0 + hop * Sz - 0.04 * Sz), vec2(0.62 * Sz, 0.56 * Sz));
    gCol *= mix(1.0, 0.35, p_halo * (1.0 - smoothstep(-0.10 * Sz, 0.30 * Sz, hh)));
  }

  // The eyes' glow, on the rings behind him: warm light spilling off the stare on the hit.
  float R = 0.170 * p_eyesize, ex = 0.190 + 0.05 * (p_eyesize - 1.0);
  float eyy = 0.305 + 0.10 * (p_eyesize - 1.0);
  float dE = min(length(c - vec2(-ex, eyy)), length(c - vec2(ex, eyy))) - R;
  vec3 glowC = p_irisc < 1.5 ? vec3(1.0, 0.80, 0.25) : hsv(fract(H + 0.05), 0.6 * p_sat, 1.0);
  gCol += glowC * exp(-max(dE, 0.0) * 7.0) * (0.10 + 0.75 * A) * p_glow;

  // Everything of him is inside this box; outside it there is nothing to draw.
  if (abs(c.x) < 0.66 && c.y > -0.56 && c.y < 0.62) toad(c, t, A, B);

  vec3 col = mix(gCol, INK, clamp(gInk, 0.0, 1.0));
  // Tint pulls the whole thing, him included, towards the show's hue. Zero leaves him alone.
  if (p_tint > 0.004) {
    float l = dot(col, vec3(0.299, 0.587, 0.114));
    col = mix(col, hsv(fract(H + 0.02), 0.75 * p_sat, 1.0) * (0.25 + 1.35 * l), p_tint);
  }

  // ---- ALL GLORY TO / THE HYPNOTOAD, top and bottom, in the cartoon's cream with a heavy ink
  // shadow, kicking brighter on the hit.
  if (cap > 0.5) {
    float hT = 0.105;
    float fp = min(hT / 7.0, 0.92 * u_aspect / 77.0);        // one font pixel, surface units
    float top = p.y > 0.0 ? 1.0 : 0.0;
    float m = 1.0 - top;
    float L = msgLen(m) * 6.0 - 1.0;
    float yb = top > 0.5 ? 0.5 - 0.035 - 7.0 * fp : -0.5 + 0.035;   // bottom edge of the line
    vec2 tq = vec2(p.x / fp + L * 0.5, (yb + 7.0 * fp - p.y) / fp);
    float px = u_px / fp;
    // A heavy ink outline all round (four offsets) and a drop shadow, like a cartoon title card.
    float ol = max(max(textCov(tq + vec2(0.45, 0.0), m, px), textCov(tq - vec2(0.45, 0.0), m, px)),
                   max(textCov(tq + vec2(0.0, 0.45), m, px), textCov(tq - vec2(0.0, 0.9), m, px)));
    ol = max(ol, textCov(tq - vec2(0.8, 0.9), m, px));
    float tc = textCov(tq, m, px);
    col = mix(col, INK * 0.5, ol);
    vec3 tcol = mix(SCLER, vec3(1.0, 0.98, 0.80), A);
    tcol *= 1.0 - 0.28 * clamp(fract(tq.y / 7.0) * 1.3 - 0.3, 0.0, 1.0);   // shaded down each letter
    col = mix(col, tcol, tc);
  }

  col *= 1.0 - 0.26 * pow(clamp(length(p * vec2(0.85, 1.25)), 0.0, 1.0), 3.0);
  return col;
}
