// Redacted: a classified document. Lines of text (grey word bars), black redaction bars over
// some words; on the beat a few bars slide away to show the hidden word glowing underneath.
// Everything is revealed on the DROP and blacked out again in the OUTRO. A stamp thumps
// down at the start of each bar. Params are p_* uniforms; ranges and defaults in redacted.json.
//
// @messages: TOP SECRET|CLASSIFIED|EYES ONLY|MAJESTIC 12|BLUE BOOK|MK ULTRA|AREA 51|PAPERCLIP|NOFORN|ROSWELL|STARGATE|THE EYE|ILLUMINATI|REPTILIAN|MOON HOAX|CONTACT
uniform float p_lines, p_margin, p_redact, p_reveal, p_every, p_drop, p_outro, p_stamp, p_stampw,
              p_dark, p_glow, p_scroll, p_hue, p_sat, p_follow, p_beat;

// <text>
// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand.
#define CH_A 1.0
#define CH_B 2.0
#define CH_C 3.0
#define CH_D 4.0
#define CH_E 5.0
#define CH_F 6.0
#define CH_G 7.0
#define CH_H 8.0
#define CH_I 9.0
#define CH_J 10.0
#define CH_K 11.0
#define CH_L 12.0
#define CH_M 13.0
#define CH_N 14.0
#define CH_O 15.0
#define CH_P 16.0
#define CH_R 17.0
#define CH_S 18.0
#define CH_T 19.0
#define CH_U 20.0
#define CH_W 21.0
#define CH_X 22.0
#define CH_Y 23.0
#define CH_1 24.0
#define CH_2 25.0
#define CH_5 26.0
vec2 glyph(float c) {
  if (c < 0.5) return vec2(0.0);
  if (c < 1.5) return vec2(1033774.0, 17969.0);   // A
  if (c < 2.5) return vec2(509487.0, 15921.0);   // B
  if (c < 3.5) return vec2(34350.0, 14881.0);   // C
  if (c < 4.5) return vec2(575023.0, 15921.0);   // D
  if (c < 5.5) return vec2(492607.0, 31777.0);   // E
  if (c < 6.5) return vec2(492607.0, 1057.0);   // F
  if (c < 7.5) return vec2(951854.0, 31281.0);   // G
  if (c < 8.5) return vec2(1033777.0, 17969.0);   // H
  if (c < 9.5) return vec2(135310.0, 14468.0);   // I
  if (c < 10.5) return vec2(270620.0, 6440.0);   // J
  if (c < 11.5) return vec2(103729.0, 17701.0);   // K
  if (c < 12.5) return vec2(33825.0, 31777.0);   // L
  if (c < 13.5) return vec2(710513.0, 17969.0);   // M
  if (c < 14.5) return vec2(708145.0, 17977.0);   // N
  if (c < 15.5) return vec2(575022.0, 14897.0);   // O
  if (c < 16.5) return vec2(509487.0, 1057.0);   // P
  if (c < 17.5) return vec2(509487.0, 17701.0);   // R
  if (c < 18.5) return vec2(459838.0, 15888.0);   // S
  if (c < 19.5) return vec2(135327.0, 4228.0);   // T
  if (c < 20.5) return vec2(575025.0, 14897.0);   // U
  if (c < 21.5) return vec2(706097.0, 10933.0);   // W
  if (c < 22.5) return vec2(141873.0, 17962.0);   // X
  if (c < 23.5) return vec2(141873.0, 4228.0);   // Y
  if (c < 24.5) return vec2(135364.0, 14468.0);   // 1
  if (c < 25.5) return vec2(279086.0, 31812.0);   // 2
  if (c < 26.5) return vec2(539711.0, 14896.0);   // 5
  return vec2(0.0);
}
float msgChunk(float m, float k) {             // three characters per float, base 64
  if (m < 0.5) { if (k < 0.5) return 66515.0; if (k < 1.5) return 21632.0; if (k < 2.5) return 21571.0; if (k < 3.5) return 19.0; return 0.0; }   // TOP SECRET
  if (m < 1.5) { if (k < 0.5) return 4867.0; if (k < 1.5) return 38034.0; if (k < 2.5) return 21062.0; if (k < 3.5) return 4.0; return 0.0; }   // CLASSIFIED
  if (m < 2.5) { if (k < 0.5) return 21957.0; if (k < 1.5) return 61458.0; if (k < 2.5) return 94990.0; return 0.0; }   // EYES ONLY
  if (m < 3.5) { if (k < 0.5) return 41037.0; if (k < 1.5) return 78981.0; if (k < 2.5) return 201.0; if (k < 3.5) return 1624.0; return 0.0; }   // MAJESTIC 12
  if (m < 4.5) { if (k < 0.5) return 82690.0; if (k < 1.5) return 8197.0; if (k < 2.5) return 46031.0; return 0.0; }   // BLUE BOOK
  if (m < 5.5) { if (k < 0.5) return 717.0; if (k < 1.5) return 78612.0; if (k < 2.5) return 81.0; return 0.0; }   // MK ULTRA
  if (m < 6.5) { if (k < 0.5) return 21569.0; if (k < 1.5) return 106497.0; if (k < 2.5) return 24.0; return 0.0; }   // AREA 51
  if (m < 7.5) { if (k < 0.5) return 65616.0; if (k < 1.5) return 13381.0; if (k < 2.5) return 66124.0; return 0.0; }   // PAPERCLIP
  if (m < 8.5) { if (k < 0.5) return 25550.0; if (k < 1.5) return 58447.0; return 0.0; }   // NOFORN
  if (m < 9.5) { if (k < 0.5) return 74705.0; if (k < 1.5) return 49493.0; if (k < 2.5) return 12.0; return 0.0; }   // ROSWELL
  if (m < 10.5) { if (k < 0.5) return 5330.0; if (k < 1.5) return 4561.0; if (k < 2.5) return 339.0; return 0.0; }   // STARGATE
  if (m < 11.5) { if (k < 0.5) return 21011.0; if (k < 1.5) return 94528.0; if (k < 2.5) return 5.0; return 0.0; }   // THE EYE
  if (m < 12.5) { if (k < 0.5) return 49929.0; if (k < 1.5) return 37716.0; if (k < 2.5) return 77902.0; if (k < 3.5) return 9.0; return 0.0; }   // ILLUMINATI
  if (m < 13.5) { if (k < 0.5) return 65873.0; if (k < 1.5) return 49747.0; if (k < 2.5) return 57417.0; return 0.0; }   // REPTILIAN
  if (m < 14.5) { if (k < 0.5) return 62413.0; if (k < 1.5) return 32782.0; if (k < 2.5) return 90191.0; return 0.0; }   // MOON HOAX
  if (m < 15.5) { if (k < 0.5) return 58307.0; if (k < 1.5) return 12371.0; if (k < 2.5) return 19.0; return 0.0; }   // CONTACT
  return 0.0;
}
float msgCount() { return 16.0; }
float msgLen(float m) {
  if (m < 0.5) return 10.0;
  if (m < 1.5) return 10.0;
  if (m < 2.5) return 9.0;
  if (m < 3.5) return 11.0;
  if (m < 4.5) return 9.0;
  if (m < 5.5) return 8.0;
  if (m < 6.5) return 7.0;
  if (m < 7.5) return 9.0;
  if (m < 8.5) return 6.0;
  if (m < 9.5) return 7.0;
  if (m < 10.5) return 8.0;
  if (m < 11.5) return 7.0;
  if (m < 12.5) return 10.0;
  if (m < 13.5) return 9.0;
  if (m < 14.5) return 9.0;
  if (m < 15.5) return 7.0;
  return 0.0;
}
float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}
float letterIndex(float c) {
  if (abs(c - 1.0) < 0.5) return 0.0;
  if (abs(c - 2.0) < 0.5) return 1.0;
  if (abs(c - 3.0) < 0.5) return 2.0;
  if (abs(c - 4.0) < 0.5) return 3.0;
  if (abs(c - 5.0) < 0.5) return 4.0;
  if (abs(c - 6.0) < 0.5) return 5.0;
  if (abs(c - 7.0) < 0.5) return 6.0;
  if (abs(c - 8.0) < 0.5) return 7.0;
  if (abs(c - 9.0) < 0.5) return 8.0;
  if (abs(c - 10.0) < 0.5) return 9.0;
  if (abs(c - 11.0) < 0.5) return 10.0;
  if (abs(c - 12.0) < 0.5) return 11.0;
  if (abs(c - 13.0) < 0.5) return 12.0;
  if (abs(c - 14.0) < 0.5) return 13.0;
  if (abs(c - 15.0) < 0.5) return 14.0;
  if (abs(c - 16.0) < 0.5) return 15.0;
  if (abs(c - 17.0) < 0.5) return 17.0;
  if (abs(c - 18.0) < 0.5) return 18.0;
  if (abs(c - 19.0) < 0.5) return 19.0;
  if (abs(c - 20.0) < 0.5) return 20.0;
  if (abs(c - 21.0) < 0.5) return 22.0;
  if (abs(c - 22.0) < 0.5) return 23.0;
  if (abs(c - 23.0) < 0.5) return 24.0;
  return -1.0;
}
// </text>

vec3 content(vec2 uv) {
  float t = u_beat;
  float k = kick() * p_beat;
  float A = u_aspect;
  bool drop = abs(u_scene - 7.0) < 0.5, outro = abs(u_scene - 8.0) < 0.5;
  vec3 paper = p_dark > 0.5 ? vec3(0.07, 0.07, 0.08) : vec3(0.93, 0.91, 0.85);
  vec3 inkc = p_dark > 0.5 ? vec3(0.32) : vec3(0.35, 0.34, 0.33);
  vec3 bar = p_dark > 0.5 ? vec3(0.0) : vec3(0.02);
  vec3 glowc = hsv(p_hue + (p_follow > 0.5 ? u_hue : 0.0), p_sat, 1.0);

  // Page coordinates: x from the left margin, y from the top, scrolling up slowly.
  vec2 P = vec2(uv.x * A, uv.y + t * p_scroll / 16.0);
  float lh = 1.0 / max(p_lines, 4.0);                       // line pitch
  float s = lh * 0.55 / 7.0;                                 // font pixel size
  float line = floor(P.y / lh);
  float ly = (P.y - line * lh) / s;                          // font pixels down this line
  float x = (P.x - p_margin * A) / s;                        // font pixels from the margin
  float width = (A * (1.0 - 2.0 * p_margin)) / s;
  float period = floor(t / max(p_every, 0.25));
  float since = fract(t / max(p_every, 0.25)) * max(p_every, 0.25);   // beats since this period began

  vec3 col = paper;
  float px = u_px / s;
  // Walk the words of this line (constant bound): each is a word bar, or a redacted word.
  float cx = 0.0;
  for (int i = 0; i < 14; i++) {
    float fi = float(i);
    vec2 id = vec2(fi, line);
    bool red = hash(id + 0.3) < p_redact;
    float m = floor(hash(id + 5.1) * msgCount());
    float wl = red ? msgLen(m) * 6.0 + 7.0 : (2.0 + floor(hash(id + 2.7) * 7.0)) * 6.0;
    if (cx + wl > width) break;
    if (x >= cx && x < cx + wl && ly > -0.5 && ly < 7.5) {
      float lx = x - cx;
      if (red && lx < wl - 5.0) {
        // Revealed this period? It slides off left to right over a quarter beat.
        float rv = hash(vec2(hash(id), period)) < p_reveal ? 1.0 : 0.0;
        if (drop) rv = max(rv, step(hash(id + 9.0), p_drop));
        if (outro) rv *= 1.0 - p_outro;
        float slide = rv * clamp(since * 4.0, 0.0, 1.0);
        float cover = step(lx, wl * (1.0 - slide));
        float tc = textCov(vec2(lx - 1.0, ly), m, px);
        vec3 under = mix(vec3(0.03), glowc, tc) + glowc * p_glow * 0.3 * (0.6 + 0.4 * k);   // dark slot, glowing word
        col = mix(under, bar, cover);
      } else if (!red) {
        // An unreadable word: a soft grey bar with ragged ends.
        float wb = step(1.0, ly) * step(ly, 6.0) * step(0.5, lx) * step(lx, wl - 6.0);
        col = mix(col, inkc, wb * (0.55 + 0.25 * hash(floor(vec2(lx, ly) * 0.5) + id)));
      }
    }
    cx += wl;
  }

  // Stamp: a message in a box, rotated, thumping down at the start of each bar.
  if (p_stamp >= 0.0) {
    float bb = mod(t, 4.0);
    float thump = 1.0 + 0.25 * exp(-bb * 6.0) * p_beat;
    vec2 c = vec2(A * 0.68, 0.24);
    vec2 d = (vec2(uv.x * A, uv.y) - c) / thump;
    float ang = -0.18;
    d = mat2(cos(ang), -sin(ang), sin(ang), cos(ang)) * d;
    float m = floor(p_stamp + 0.5);
    float ss = p_stampw * A / (msgLen(m) * 6.0 + 6.0);
    vec2 q = d / ss + vec2(msgLen(m) * 3.0, 3.5);
    float tc = textCov(q, m, u_px / ss);
    vec2 bd = abs(d) - vec2(msgLen(m) * 3.0 + 3.0, 7.0) * ss;
    float boxl = 1.0 - smoothstep(0.6 * ss - u_px, 0.6 * ss + u_px, abs(max(bd.x, bd.y)));
    float wear = 0.65 + 0.35 * hash(floor(d / ss * 1.5));
    col = mix(col, vec3(0.8, 0.08, 0.06), clamp(tc + boxl, 0.0, 1.0) * wear * 0.85);
  }
  return col * (0.9 + 0.1 * k);
}
