// Subliminal: They Live-style messages flashed in time. Modes:
//   0 Flash: the word shows for Hold beats at the start of each bar
//   1 Strobe: on every beat for Hold of the beat
//   2 Steady: always on, changing each bar, with glitch
//   3 Reveal: hidden behind a bland "broadcast" until the DROP; flickers through in a BUILD
// Words come from the @messages list: First picks where to start, Count how many to use.
// Params are p_* uniforms; ranges and defaults are in subliminal.json.
//
// @messages: OBEY|CONSUME|SUBMIT|CONFORM|STAY ASLEEP|WATCH TV|NO THOUGHT|BUY|SLEEP|WAKE UP|THEY LIVE|TRUST NO ONE|THEY ARE WATCHING|QUESTION EVERYTHING|THE TRUTH IS OUT THERE|DO NOT RESIST
uniform float p_mode, p_first, p_count, p_random, p_hold, p_size, p_invert, p_bg, p_glitch, p_jitter,
              p_grain, p_hue, p_sat, p_follow, p_beat;

// <text>
// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand.
#define CH_A 1.0
#define CH_B 2.0
#define CH_C 3.0
#define CH_D 4.0
#define CH_E 5.0
#define CH_F 6.0
#define CH_G 7.0
#define CH_H 8.0
#define CH_I 9.0
#define CH_K 10.0
#define CH_L 11.0
#define CH_M 12.0
#define CH_N 13.0
#define CH_O 14.0
#define CH_P 15.0
#define CH_Q 16.0
#define CH_R 17.0
#define CH_S 18.0
#define CH_T 19.0
#define CH_U 20.0
#define CH_V 21.0
#define CH_W 22.0
#define CH_Y 23.0
vec2 glyph(float c) {
  if (c < 0.5) return vec2(0.0);
  if (c < 1.5) return vec2(1033774.0, 17969.0);   // A
  if (c < 2.5) return vec2(509487.0, 15921.0);   // B
  if (c < 3.5) return vec2(34350.0, 14881.0);   // C
  if (c < 4.5) return vec2(575023.0, 15921.0);   // D
  if (c < 5.5) return vec2(492607.0, 31777.0);   // E
  if (c < 6.5) return vec2(492607.0, 1057.0);   // F
  if (c < 7.5) return vec2(951854.0, 31281.0);   // G
  if (c < 8.5) return vec2(1033777.0, 17969.0);   // H
  if (c < 9.5) return vec2(135310.0, 14468.0);   // I
  if (c < 10.5) return vec2(103729.0, 17701.0);   // K
  if (c < 11.5) return vec2(33825.0, 31777.0);   // L
  if (c < 12.5) return vec2(710513.0, 17969.0);   // M
  if (c < 13.5) return vec2(708145.0, 17977.0);   // N
  if (c < 14.5) return vec2(575022.0, 14897.0);   // O
  if (c < 15.5) return vec2(509487.0, 1057.0);   // P
  if (c < 16.5) return vec2(575022.0, 22837.0);   // Q
  if (c < 17.5) return vec2(509487.0, 17701.0);   // R
  if (c < 18.5) return vec2(459838.0, 15888.0);   // S
  if (c < 19.5) return vec2(135327.0, 4228.0);   // T
  if (c < 20.5) return vec2(575025.0, 14897.0);   // U
  if (c < 21.5) return vec2(575025.0, 4433.0);   // V
  if (c < 22.5) return vec2(706097.0, 10933.0);   // W
  if (c < 23.5) return vec2(141873.0, 4228.0);   // Y
  return vec2(0.0);
}
float msgChunk(float m, float k) {             // three characters per float, base 64
  if (m < 0.5) { if (k < 0.5) return 20622.0; if (k < 1.5) return 23.0; return 0.0; }   // OBEY
  if (m < 1.5) { if (k < 0.5) return 54147.0; if (k < 1.5) return 50450.0; if (k < 2.5) return 5.0; return 0.0; }   // CONSUME
  if (m < 2.5) { if (k < 0.5) return 9490.0; if (k < 1.5) return 78412.0; return 0.0; }   // SUBMIT
  if (m < 3.5) { if (k < 0.5) return 54147.0; if (k < 1.5) return 70534.0; if (k < 2.5) return 12.0; return 0.0; }   // CONFORM
  if (m < 4.5) { if (k < 0.5) return 5330.0; if (k < 1.5) return 4119.0; if (k < 2.5) return 21202.0; if (k < 3.5) return 965.0; return 0.0; }   // STAY ASLEEP
  if (m < 5.5) { if (k < 0.5) return 77910.0; if (k < 1.5) return 515.0; if (k < 2.5) return 1363.0; return 0.0; }   // WATCH TV
  if (m < 6.5) { if (k < 0.5) return 909.0; if (k < 1.5) return 57875.0; if (k < 2.5) return 33236.0; if (k < 3.5) return 19.0; return 0.0; }   // NO THOUGHT
  if (m < 7.5) { if (k < 0.5) return 95490.0; return 0.0; }   // BUY
  if (m < 8.5) { if (k < 0.5) return 21202.0; if (k < 1.5) return 965.0; return 0.0; }   // SLEEP
  if (m < 9.5) { if (k < 0.5) return 41046.0; if (k < 1.5) return 81925.0; if (k < 2.5) return 15.0; return 0.0; }   // WAKE UP
  if (m < 10.5) { if (k < 0.5) return 21011.0; if (k < 1.5) return 45079.0; if (k < 2.5) return 21833.0; return 0.0; }   // THEY LIVE
  if (m < 11.5) { if (k < 0.5) return 83027.0; if (k < 1.5) return 1234.0; if (k < 2.5) return 909.0; if (k < 3.5) return 21326.0; return 0.0; }   // TRUST NO ONE
  if (m < 12.5) { if (k < 0.5) return 21011.0; if (k < 1.5) return 4119.0; if (k < 2.5) return 337.0; if (k < 3.5) return 77910.0; if (k < 4.5) return 37379.0; if (k < 5.5) return 461.0; return 0.0; }   // THEY ARE WATCHING
  if (m < 13.5) { if (k < 0.5) return 21776.0; if (k < 1.5) return 38098.0; if (k < 2.5) return 846.0; if (k < 3.5) return 21829.0; if (k < 4.5) return 79313.0; if (k < 5.5) return 53832.0; if (k < 6.5) return 7.0; return 0.0; }   // QUESTION EVERYTHING
  if (m < 14.5) { if (k < 0.5) return 21011.0; if (k < 1.5) return 70848.0; if (k < 2.5) return 34004.0; if (k < 3.5) return 74304.0; if (k < 4.5) return 82816.0; if (k < 5.5) return 77843.0; if (k < 6.5) return 69960.0; if (k < 7.5) return 5.0; return 0.0; }   // THE TRUTH IS OUT THERE
  if (m < 15.5) { if (k < 0.5) return 900.0; if (k < 1.5) return 78733.0; if (k < 2.5) return 21568.0; if (k < 3.5) return 74322.0; if (k < 4.5) return 19.0; return 0.0; }   // DO NOT RESIST
  return 0.0;
}
float msgCount() { return 16.0; }
float msgLen(float m) {
  if (m < 0.5) return 4.0;
  if (m < 1.5) return 7.0;
  if (m < 2.5) return 6.0;
  if (m < 3.5) return 7.0;
  if (m < 4.5) return 11.0;
  if (m < 5.5) return 8.0;
  if (m < 6.5) return 10.0;
  if (m < 7.5) return 3.0;
  if (m < 8.5) return 5.0;
  if (m < 9.5) return 7.0;
  if (m < 10.5) return 9.0;
  if (m < 11.5) return 12.0;
  if (m < 12.5) return 17.0;
  if (m < 13.5) return 19.0;
  if (m < 14.5) return 22.0;
  if (m < 15.5) return 13.0;
  return 0.0;
}
float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}
float letterIndex(float c) {
  if (abs(c - 1.0) < 0.5) return 0.0;
  if (abs(c - 2.0) < 0.5) return 1.0;
  if (abs(c - 3.0) < 0.5) return 2.0;
  if (abs(c - 4.0) < 0.5) return 3.0;
  if (abs(c - 5.0) < 0.5) return 4.0;
  if (abs(c - 6.0) < 0.5) return 5.0;
  if (abs(c - 7.0) < 0.5) return 6.0;
  if (abs(c - 8.0) < 0.5) return 7.0;
  if (abs(c - 9.0) < 0.5) return 8.0;
  if (abs(c - 10.0) < 0.5) return 10.0;
  if (abs(c - 11.0) < 0.5) return 11.0;
  if (abs(c - 12.0) < 0.5) return 12.0;
  if (abs(c - 13.0) < 0.5) return 13.0;
  if (abs(c - 14.0) < 0.5) return 14.0;
  if (abs(c - 15.0) < 0.5) return 15.0;
  if (abs(c - 16.0) < 0.5) return 16.0;
  if (abs(c - 17.0) < 0.5) return 17.0;
  if (abs(c - 18.0) < 0.5) return 18.0;
  if (abs(c - 19.0) < 0.5) return 19.0;
  if (abs(c - 20.0) < 0.5) return 20.0;
  if (abs(c - 21.0) < 0.5) return 21.0;
  if (abs(c - 22.0) < 0.5) return 22.0;
  if (abs(c - 23.0) < 0.5) return 24.0;
  return -1.0;
}
// </text>

vec3 content(vec2 uv) {
  float t = u_beat;
  float k = kick() * p_beat;
  float bar = floor(t / 4.0), bb = mod(t, 4.0);
  float n = max(1.0, min(p_count, msgCount() - p_first));
  float m = p_first + (p_random > 0.5 ? floor(hash(vec2(bar, 2.1)) * n) : mod(bar, n));
  bool drop = abs(u_scene - 7.0) < 0.5, build = abs(u_scene - 4.0) < 0.5 || abs(u_scene - 6.0) < 0.5;

  // Is the word showing right now?
  float on = 0.0;
  if (p_mode < 0.5) on = step(bb, p_hold);
  else if (p_mode < 1.5) { on = step(u_frac, p_hold); m = p_first + mod(floor(t), n); }
  else if (p_mode < 2.5) on = 1.0;
  else {
    on = drop ? 1.0 : 0.0;
    if (build) on = step(hash(vec2(floor(t * 4.0), 5.3)), u_sp * 0.6);
  }

  // Fit the word: height Size, never wider than 92% of the surface.
  float len = msgLen(m);
  float wpx = len * 6.0 - 1.0;
  float s = min(p_size / 7.0, 0.92 * u_aspect / wpx);
  vec2 P = (uv - 0.5) * vec2(u_aspect, 1.0);
  float jf = floor(u_time * 24.0);
  P += p_jitter * 0.012 * (vec2(hash(vec2(jf, 1.0)), hash(vec2(jf, 2.0))) - 0.5) * (0.4 + k);
  vec2 q = (P + vec2(wpx, 7.0) * s * 0.5) / s;
  float px = u_px / s;
  float sh = p_glitch * (0.6 + 2.0 * k) * 0.8;          // RGB split, in font pixels
  vec3 cov = p_glitch > 0.01
    ? vec3(textCov(q + vec2(sh, 0.0), m, px), textCov(q, m, px), textCov(q - vec2(sh, 0.0), m, px))
    : vec3(textCov(q, m, px));
  cov *= on;

  // Background: black, a flash on the word, or the bland broadcast in Reveal mode.
  vec3 ink = p_sat < 0.01 ? vec3(1.0) : hsv(p_hue + (p_follow > 0.5 ? u_hue : 0.0), p_sat, 1.0);
  vec3 bg = vec3(p_bg * on * (0.25 + 0.75 * k));
  if (p_mode > 2.5 && on < 0.5) {
    float g = 0.5 + 0.5 * sin(uv.x * 3.0 + t * 0.2) * cos(uv.y * 2.0 - t * 0.13);
    bg = mix(vec3(0.25, 0.45, 0.7), vec3(0.95, 0.7, 0.55), g) * 0.55;
  }
  vec3 col = p_invert > 0.5 && on > 0.5 ? mix(vec3(0.95), vec3(0.0), cov) : bg + (1.0 - bg) * ink * cov;
  col += (hash(uv * 731.0 + fract(u_time) * 17.0) - 0.5) * p_grain * 0.25;
  col *= 1.0 - p_grain * 0.25 * (0.5 + 0.5 * sin(uv.y * 900.0));
  return clamp(col, 0.0, 1.0);
}
