// Topo: a topographic contour map of slowly evolving terrain (after "Topographic Contour
// Map" in Paul Bakaus's Radiant collection, MIT). The original extracts isolines with
// marching squares; here each pixel measures its distance to the nearest contour level
// from the height and its gradient, so lines stay one width everywhere. Every 5th contour
// is major (thicker, brighter, with elevation labels on a dark knockout). Beat: the lines
// punch on the kick, a peak in the middle swells, and the levels can scroll so the rings
// march up or down the hills. Params are p_* uniforms; ranges and defaults are in topo.json.
uniform float p_scale, p_contrast, p_evolve, p_levels, p_width, p_glow, p_scroll,
              p_punch, p_peak, p_radius, p_pulse, p_labels, p_lsize, p_lspace,
              p_tint, p_hue, p_spread, p_sat, p_bright, p_bg, p_vignette, p_follow;

// @messages: 0123456789
// <text>
// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand.
#define CH_0 1.0
#define CH_1 2.0
#define CH_2 3.0
#define CH_3 4.0
#define CH_4 5.0
#define CH_5 6.0
#define CH_6 7.0
#define CH_7 8.0
#define CH_8 9.0
#define CH_9 10.0
vec2 glyph(float c) {
  if (c < 0.5) return vec2(0.0);
  if (c < 1.5) return vec2(714286.0, 14899.0);   // 0
  if (c < 2.5) return vec2(135364.0, 14468.0);   // 1
  if (c < 3.5) return vec2(279086.0, 31812.0);   // 2
  if (c < 4.5) return vec2(266527.0, 14896.0);   // 3
  if (c < 5.5) return vec2(305544.0, 8479.0);   // 4
  if (c < 6.5) return vec2(539711.0, 14896.0);   // 5
  if (c < 7.5) return vec2(492620.0, 14897.0);   // 6
  if (c < 8.5) return vec2(139807.0, 2114.0);   // 7
  if (c < 9.5) return vec2(476718.0, 14897.0);   // 8
  if (c < 10.5) return vec2(1001006.0, 6416.0);   // 9
  return vec2(0.0);
}
float msgChunk(float m, float k) {             // three characters per float, base 64
  if (m < 0.5) { if (k < 0.5) return 12417.0; if (k < 1.5) return 24900.0; if (k < 2.5) return 37383.0; if (k < 3.5) return 10.0; return 0.0; }   // 0123456789
  return 0.0;
}
float msgCount() { return 1.0; }
float msgLen(float m) {
  if (m < 0.5) return 10.0;
  return 0.0;
}
float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}
float letterIndex(float c) {
  return -1.0;
}
// </text>

// 3D simplex noise (Ian McEwan, Ashima Arts; MIT).
vec4 permute(vec4 x) { return mod(((x * 34.0) + 1.0) * x, 289.0); }
vec4 taylorInvSqrt(vec4 r) { return 1.79284291400159 - 0.85373472095314 * r; }
float snoise(vec3 v) {
  const vec2 C = vec2(1.0 / 6.0, 1.0 / 3.0);
  const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);
  vec3 i = floor(v + dot(v, C.yyy));
  vec3 x0 = v - i + dot(i, C.xxx);
  vec3 g = step(x0.yzx, x0.xyz);
  vec3 l = 1.0 - g;
  vec3 i1 = min(g.xyz, l.zxy);
  vec3 i2 = max(g.xyz, l.zxy);
  vec3 x1 = x0 - i1 + C.xxx;
  vec3 x2 = x0 - i2 + C.yyy;
  vec3 x3 = x0 - D.yyy;
  i = mod(i, 289.0);
  vec4 p = permute(permute(permute(i.z + vec4(0.0, i1.z, i2.z, 1.0))
                                 + i.y + vec4(0.0, i1.y, i2.y, 1.0))
                                 + i.x + vec4(0.0, i1.x, i2.x, 1.0));
  vec3 ns = (1.0 / 7.0) * D.wyz - D.xzx;
  vec4 j = p - 49.0 * floor(p * ns.z * ns.z);
  vec4 x_ = floor(j * ns.z);
  vec4 y_ = floor(j - 7.0 * x_);
  vec4 x = x_ * ns.x + ns.yyyy;
  vec4 y = y_ * ns.x + ns.yyyy;
  vec4 h = 1.0 - abs(x) - abs(y);
  vec4 b0 = vec4(x.xy, y.xy);
  vec4 b1 = vec4(x.zw, y.zw);
  vec4 s0 = floor(b0) * 2.0 + 1.0;
  vec4 s1 = floor(b1) * 2.0 + 1.0;
  vec4 sh = -step(h, vec4(0.0));
  vec4 a0 = b0.xzyw + s0.xzyw * sh.xxyy;
  vec4 a1 = b1.xzyw + s1.xzyw * sh.zzww;
  vec3 p0 = vec3(a0.xy, h.x);
  vec3 p1 = vec3(a0.zw, h.y);
  vec3 p2 = vec3(a1.xy, h.z);
  vec3 p3 = vec3(a1.zw, h.w);
  vec4 nrm = taylorInvSqrt(vec4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
  p0 *= nrm.x; p1 *= nrm.y; p2 *= nrm.z; p3 *= nrm.w;
  vec4 m = max(0.6 - vec4(dot(x0, x0), dot(x1, x1), dot(x2, x2), dot(x3, x3)), 0.0);
  m = m * m;
  return 42.0 * dot(m * m, vec4(dot(p0, x0), dot(p1, x1), dot(p2, x2), dot(p3, x3)));
}

// Height 0..1 at q (surface heights from the centre): 4 octaves as in the original, plus
// the peak in the middle (the original's mouse peak), which swells on the kick.
float height(vec2 q, float z, float k) {
  float val = 0.0, amp = 1.0, freq = 1.0, sum = 0.0;
  for (int o = 0; o < 4; o++) {
    val += snoise(vec3(q * p_scale * freq, z)) * amp;
    sum += amp;
    amp *= 0.5;
    freq *= 2.0;
  }
  val /= sum;
  float fall = max(1.0 - length(q) / max(p_radius, 1e-3), 0.0);
  val += (p_peak + p_pulse * k) * fall * fall;
  return 0.5 + 0.5 * val * p_contrast;
}

// Height and its gradient (per surface height), by forward differences.
vec3 heightGrad(vec2 q, float z, float k) {
  const float e = 0.002;
  float h0 = height(q, z, k);
  return vec3(h0, (height(q + vec2(e, 0.0), z, k) - h0) / e, (height(q + vec2(0.0, e), z, k) - h0) / e);
}

// The original's ramp: deep coral at the lowest contour, amber in the middle, gold at the top.
vec3 ramp(float t) {
  vec3 coral = vec3(224.0, 120.0, 80.0) / 255.0;
  vec3 amber = vec3(200.0, 149.0, 108.0) / 255.0;
  vec3 gold  = vec3(212.0, 165.0, 116.0) / 255.0;
  vec3 c = t < 0.5 ? mix(coral, amber, t * 2.0) : mix(amber, gold, (t - 0.5) * 2.0);
  float lum = dot(c, vec3(0.299, 0.587, 0.114));
  vec3 tinted = hsv(mix(p_hue, u_hue, p_follow) + (t - 0.5) * p_spread, p_sat, lum * 1.25);
  return mix(c, tinted, p_tint) * p_bright;
}

float lineCov(float dpx, float w) {           // a line w px wide, box-filtered to the pixel
  float wc = max(w, 1.0);
  return clamp(0.5 * wc + 0.5 - dpx, 0.0, 1.0) * (w / wc);
}

vec3 content(vec2 uv) {
  float k = kick();
  vec2 p = (uv - 0.5) * vec2(u_aspect, 1.0);
  float z = u_beat * p_evolve;
  float n1 = p_levels + 1.0;
  float S = u_beat * p_scroll;                 // level offset: contours march with the beat

  vec3 col = vec3(p_bg);

  // Contours: level j sits at height (j - S) / (levels + 1); the original draws levels 1..N.
  vec3 hg = heightGrad(p, z, k);
  float L = hg.x * n1 + S;
  float j = floor(L + 0.5);
  float t = (j - S) / n1;                      // this contour's height, 0..1
  float dpx = abs(L - j) / n1 / max(length(hg.yz), 1e-4) / u_px;
  float inRange = smoothstep(0.0, 0.5 / n1, t) * (1.0 - smoothstep(1.0 - 0.5 / n1, 1.0, t));
  bool major = abs(mod(j, 5.0)) < 0.5;
  vec3 lc = ramp(clamp(t, 0.0, 1.0));
  float base = (0.25 + (1.0 - abs(t - 0.5) * 2.0) * 0.45) * (1.0 + p_punch * k) * inRange;
  float gw = (major ? 4.5 : 2.5) * p_width;
  float sw = (major ? 1.2 : 0.6) * p_width;
  float glow = (1.0 - smoothstep(0.0, 0.5 * gw + 0.5, dpx)) * base * 0.25 * p_glow;
  col = mix(col, lc, clamp(glow, 0.0, 1.0));
  col = mix(col, lc, clamp(lineCov(dpx, sw) * base * (major ? 1.0 : 0.8), 0.0, 1.0));

  // Elevation labels: at most one per cell, sitting on the nearest major contour to a
  // random anchor, turned along it and kept upright, on a dark knockout.
  if (p_labels > 0.0) {
    vec2 cell = floor(p / p_lspace);
    if (hash(cell + 0.5) < p_labels) {
      vec2 a = (cell + 0.3 + 0.4 * vec2(hash(cell + 1.7), hash(cell + 4.1))) * p_lspace;
      vec3 ag = heightGrad(a, z, k);
      float jm = floor((ag.x * n1 + S) / 5.0 + 0.5) * 5.0;
      float tm = (jm - S) / n1;
      float g2 = max(dot(ag.yz, ag.yz), 1e-6);
      vec2 a2 = a + (tm - ag.x) * ag.yz / g2;   // step onto the contour
      vec2 auv = a2 / vec2(u_aspect, 1.0) + 0.5;
      bool ok = length(a2 - a) < 0.15 * p_lspace && tm > 0.02 && tm < 0.98
             && auv.x > 0.06 && auv.x < 0.94 && auv.y > 0.05 && auv.y < 0.95;
      if (ok) {
        vec2 tv = normalize(vec2(-ag.z, ag.y));
        if (tv.x < 0.0) tv = -tv;
        vec2 nv = vec2(-tv.y, tv.x);
        float e = floor(tm * 1000.0 + 0.5);
        float nd = e >= 1000.0 ? 4.0 : (e >= 100.0 ? 3.0 : (e >= 10.0 ? 2.0 : 1.0));
        float wf = nd * 6.0 - 1.0;              // text width in font pixels
        vec2 rel = p - a2;
        vec2 f = vec2(dot(rel, tv), dot(rel, nv)) / p_lsize + vec2(0.5 * wf, 3.5);
        vec2 fc = f - vec2(0.5 * wf, 3.5);
        if (abs(fc.x) < 0.5 * wf + 3.0 && abs(fc.y) < 6.0) {
          col = mix(col, vec3(10.0 / 255.0), 0.85);
          float i = floor(f.x / 6.0);
          if (i >= 0.0 && i < nd) {
            float digit = mod(floor(e / pow(10.0, nd - 1.0 - i) + 0.001), 10.0);
            float cov = charCov(vec2(f.x - 6.0 * i, f.y), CH_0 + digit, u_px / p_lsize);
            vec3 tc = ramp(clamp(tm, 0.0, 1.0));
            col = mix(col, tc, cov * (0.25 + (1.0 - abs(tm - 0.5) * 2.0) * 0.45) * 0.6 * 1.6);
          }
        }
      }
    }
  }

  // Vignette, as in the original: clear inside 0.3 of the short side, 40% dark at 0.75 of the long.
  float r = length(p);
  float r0 = 0.3 * min(u_aspect, 1.0), r1 = 0.75 * max(u_aspect, 1.0);
  col = mix(col, vec3(10.0 / 255.0), p_vignette * clamp((r - r0) / (r1 - r0), 0.0, 1.0));
  return col;
}
