#!/usr/bin/env python3
"""Put a 5x7 pixel font and a list of messages into a sketch, so shaders can draw words.

A sketch that wants text has a line listing its messages and a block for the generated code:

    // @messages: OBEY|CONSUME|WAKE UP
    // <text>
    // </text>

Running this regenerates everything between the markers:

    python3 brain/visuals/tools/glsltext.py brain/visuals/sketches/subliminal.glsl

The block defines, for the shader to use:
    float msgCount()                  number of messages
    float msgLen(float m)             characters in message m (0-based)
    float textCov(vec2 q, float m, float px)
        coverage (0..1) of message m at q, in font pixels: x from the start of the line
        (6 per character, 5 drawn + 1 gap), y from the top (7 rows). px is one output pixel
        in font pixels, for anti-aliasing.
    float charCov(vec2 q, float c, float px)   one character code c, q as above (0..6, 0..7)
    float msgChar(float m, float i)            the code of character i of message m
    float letterIndex(float c)                 0..25 for A..Z, -1 otherwise
    #define CH_A, CH_0, ...                    codes of the letters and digits used, so a shader
                                               can draw live numbers (put 0123456789 in a message)

Messages are A-Z, 0-9, space and : - . ! ? / # ' only. Only the characters used are
included. No bitwise ops (WebGL1): each glyph is two floats (rows 0-3, rows 4-6, five bits
a row), and bits come out by dividing by exact powers of two, which is exact in highp.
"""
import re
import sys

FONT = {
    "A": ".###.|#...#|#...#|#####|#...#|#...#|#...#", "B": "####.|#...#|#...#|####.|#...#|#...#|####.",
    "C": ".###.|#...#|#....|#....|#....|#...#|.###.", "D": "####.|#...#|#...#|#...#|#...#|#...#|####.",
    "E": "#####|#....|#....|####.|#....|#....|#####", "F": "#####|#....|#....|####.|#....|#....|#....",
    "G": ".###.|#...#|#....|#.###|#...#|#...#|.####", "H": "#...#|#...#|#...#|#####|#...#|#...#|#...#",
    "I": ".###.|..#..|..#..|..#..|..#..|..#..|.###.", "J": "..###|...#.|...#.|...#.|...#.|#..#.|.##..",
    "K": "#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#", "L": "#....|#....|#....|#....|#....|#....|#####",
    "M": "#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#", "N": "#...#|#...#|##..#|#.#.#|#..##|#...#|#...#",
    "O": ".###.|#...#|#...#|#...#|#...#|#...#|.###.", "P": "####.|#...#|#...#|####.|#....|#....|#....",
    "Q": ".###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#", "R": "####.|#...#|#...#|####.|#.#..|#..#.|#...#",
    "S": ".####|#....|#....|.###.|....#|....#|####.", "T": "#####|..#..|..#..|..#..|..#..|..#..|..#..",
    "U": "#...#|#...#|#...#|#...#|#...#|#...#|.###.", "V": "#...#|#...#|#...#|#...#|#...#|.#.#.|..#..",
    "W": "#...#|#...#|#...#|#.#.#|#.#.#|#.#.#|.#.#.", "X": "#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#",
    "Y": "#...#|#...#|.#.#.|..#..|..#..|..#..|..#..", "Z": "#####|....#|...#.|..#..|.#...|#....|#####",
    "0": ".###.|#...#|#..##|#.#.#|##..#|#...#|.###.", "1": "..#..|.##..|..#..|..#..|..#..|..#..|.###.",
    "2": ".###.|#...#|....#|...#.|..#..|.#...|#####", "3": "#####|...#.|..#..|...#.|....#|#...#|.###.",
    "4": "...#.|..##.|.#.#.|#..#.|#####|...#.|...#.", "5": "#####|#....|####.|....#|....#|#...#|.###.",
    "6": "..##.|.#...|#....|####.|#...#|#...#|.###.", "7": "#####|....#|...#.|..#..|.#...|.#...|.#...",
    "8": ".###.|#...#|#...#|.###.|#...#|#...#|.###.", "9": ".###.|#...#|#...#|.####|....#|...#.|.##..",
    ":": ".....|.##..|.##..|.....|.##..|.##..|.....", "-": ".....|.....|.....|#####|.....|.....|.....",
    ".": ".....|.....|.....|.....|.....|.##..|.##..", "!": "..#..|..#..|..#..|..#..|..#..|.....|..#..",
    "?": ".###.|#...#|....#|...#.|..#..|.....|..#..", "/": "....#|....#|...#.|..#..|.#...|#....|#....",
    "#": ".#.#.|.#.#.|#####|.#.#.|#####|.#.#.|.#.#.", "'": "..#..|..#..|.#...|.....|.....|.....|.....",
}


def glyph_floats(ch):
    rows = FONT[ch].split("|")
    bits = [1 if c == "#" else 0 for r in rows for c in r]
    lo = sum(b << i for i, b in enumerate(bits[:20]))
    hi = sum(b << i for i, b in enumerate(bits[20:]))
    return lo, hi


def f(x):
    return f"{float(x):.1f}"


def generate(messages):
    chars = sorted({c for m in messages for c in m if c != " "}, key=lambda c: list(FONT).index(c))
    code = {c: i + 1 for i, c in enumerate(chars)}            # 0 = space
    out = ["// Generated by brain/visuals/tools/glsltext.py from the @messages line. Don't edit by hand."]
    for c in chars:
        if c.isalnum():
            out.append(f"#define CH_{c} {f(code[c])}")
    out.append("vec2 glyph(float c) {")
    out.append("  if (c < 0.5) return vec2(0.0);")
    for c in chars:
        lo, hi = glyph_floats(c)
        out.append(f"  if (c < {code[c] + 0.5}) return vec2({f(lo)}, {f(hi)});   // {c}")
    out.append("  return vec2(0.0);\n}")
    out.append("float msgChunk(float m, float k) {             // three characters per float, base 64")
    for mi, msg in enumerate(messages):
        cs = [code.get(c, 0) for c in msg]
        chunks = [cs[i:i + 3] for i in range(0, len(cs), 3)]
        body = " ".join(f"if (k < {ki + 0.5}) return {f(sum(v * 64 ** j for j, v in enumerate(ch)))};"
                        for ki, ch in enumerate(chunks))
        out.append(f"  if (m < {mi + 0.5}) {{ {body} return 0.0; }}   // {msg}")
    out.append("  return 0.0;\n}")
    out.append(f"float msgCount() {{ return {f(len(messages))}; }}")
    out.append("float msgLen(float m) {")
    for mi, msg in enumerate(messages):
        out.append(f"  if (m < {mi + 0.5}) return {f(len(msg))};")
    out.append("  return 0.0;\n}")
    out.append("""float msgChar(float m, float i) {
  float v = msgChunk(m, floor(i / 3.0)), j = mod(i, 3.0);
  return mod(floor(v / (j < 0.5 ? 1.0 : j < 1.5 ? 64.0 : 4096.0)), 64.0);
}
float glyphBit(vec2 g, vec2 cell) {                 // cell: column 0..4, row 0..6 from the top
  if (cell.x < 0.0 || cell.x > 4.0 || cell.y < 0.0 || cell.y > 6.0) return 0.0;
  float v = cell.y < 3.5 ? g.x : g.y, r = cell.y < 3.5 ? cell.y : cell.y - 4.0;
  float row = mod(floor(v / (r < 0.5 ? 1.0 : r < 1.5 ? 32.0 : r < 2.5 ? 1024.0 : 32768.0)), 32.0);
  float x = cell.x;
  return mod(floor(row / (x < 0.5 ? 1.0 : x < 1.5 ? 2.0 : x < 2.5 ? 4.0 : x < 3.5 ? 8.0 : 16.0)), 2.0);
}
float charCov(vec2 q, float c, float px) {
  if (c < 0.5 || q.x < -1.0 || q.x > 6.0 || q.y < -1.0 || q.y > 8.0) return 0.0;
  vec2 g = glyph(c);
  vec2 s = q - 0.5, i0 = floor(s), fr = fract(s);
  float v = mix(mix(glyphBit(g, i0), glyphBit(g, i0 + vec2(1.0, 0.0)), fr.x),
                mix(glyphBit(g, i0 + vec2(0.0, 1.0)), glyphBit(g, i0 + vec2(1.0, 1.0)), fr.x), fr.y);
  float w = max(px, 0.02);
  return smoothstep(0.4 - w, 0.4 + w, v);             // below 0.5: bolder, diagonals join
}
float textCov(vec2 q, float m, float px) {
  float ci = floor(q.x / 6.0);
  if (ci < 0.0 || ci >= msgLen(m)) return 0.0;
  return charCov(q - vec2(ci * 6.0, 0.0), msgChar(m, ci), px);
}""")
    letters = [c for c in chars if c.isalpha()]
    out.append("float letterIndex(float c) {")
    for c in letters:
        out.append(f"  if (abs(c - {f(code[c])}) < 0.5) return {f(ord(c) - 65)};")
    out.append("  return -1.0;\n}")
    return "\n".join(out)


def main(paths):
    for p in paths:
        src = open(p).read()
        m = re.search(r"^// @messages:(.*)$", src, re.M)
        if not m:
            sys.exit(f"{p}: no '// @messages:' line")
        messages = [s.strip().upper() for s in m.group(1).split("|") if s.strip()]
        bad = {c for s in messages for c in s if c != " " and c not in FONT}
        if bad:
            sys.exit(f"{p}: characters not in the font: {''.join(sorted(bad))}")
        new, n = re.subn(r"// <text>\n.*?// </text>", lambda _: "// <text>\n" + generate(messages) + "\n// </text>",
                         src, flags=re.S)
        if not n:
            sys.exit(f"{p}: no '// <text>' ... '// </text>' block")
        open(p, "w").write(new)
        print(f"{p}: {len(messages)} messages")


if __name__ == "__main__":
    main(sys.argv[1:])
